IF COL_LENGTH('CBDB_REPORTS.DMS.ACCOUNT_BAL_HISTORY', 'CHANNEL_TYPE') IS NULL
BEGIN
	ALTER TABLE CBDB_REPORTS.DMS.ACCOUNT_BAL_HISTORY
	ADD CHANNEL_TYPE SMALLINT
END

IF COL_LENGTH('CBDB_REPORTS.DMS.ACCOUNT_BAL_HISTORY', 'AVAILABLE_BALANCE') IS NULL
BEGIN
	ALTER TABLE CBDB_REPORTS.DMS.ACCOUNT_BAL_HISTORY
	ADD AVAILABLE_BALANCE DECIMAL(18,2)
END

IF COL_LENGTH('CBDB_REPORTS.DMS.ACCOUNT_BAL_HISTORY', 'FLOAT_BALANCE') IS NULL
BEGIN
	ALTER TABLE CBDB_REPORTS.DMS.ACCOUNT_BAL_HISTORY
	ADD FLOAT_BALANCE DECIMAL(18,2)
END

IF COL_LENGTH('CBDB_REPORTS.DMS.ACCOUNT_BAL_HISTORY', 'LEDGER_BALANCE') IS NULL
BEGIN
	ALTER TABLE CBDB_REPORTS.DMS.ACCOUNT_BAL_HISTORY
	ADD LEDGER_BALANCE DECIMAL(18,2)
END


