IF COL_LENGTH('CBDB_REPORTS.LMS.ACCT_BAL_HISTORY', 'BRANCH_CODE') IS NULL
BEGIN
	ALTER TABLE CBDB_REPORTS.LMS.ACCT_BAL_HISTORY
	ADD BRANCH_CODE NVARCHAR(20)
END

IF COL_LENGTH('CBDB_REPORTS.LMS.ACCT_BAL_HISTORY', 'PRINCIPAL_BALANCE') IS NULL
BEGIN
	ALTER TABLE CBDB_REPORTS.LMS.ACCT_BAL_HISTORY
	ADD PRINCIPAL_BALANCE NUMERIC(15,2)
END

IF COL_LENGTH('CBDB_REPORTS.LMS.ACCT_BAL_HISTORY', 'INTEREST_BALANCE') IS NULL
BEGIN
	ALTER TABLE CBDB_REPORTS.LMS.ACCT_BAL_HISTORY
	ADD INTEREST_BALANCE NUMERIC(15,2)
END


IF COL_LENGTH('CBDB_REPORTS.LMS.ACCT_BAL_HISTORY', 'AIR_BALANCE') IS NULL
BEGIN
	ALTER TABLE CBDB_REPORTS.LMS.ACCT_BAL_HISTORY
	ADD AIR_BALANCE NUMERIC(15,2)
END


IF COL_LENGTH('CBDB_REPORTS.LMS.ACCT_BAL_HISTORY', 'DEPOSIT_ACCOUNT_NO') IS NULL
BEGIN
	ALTER TABLE CBDB_REPORTS.LMS.ACCT_BAL_HISTORY
	ADD DEPOSIT_ACCOUNT_NO NVARCHAR(30)
END




