DROP TABLE IF EXISTS CBDB_REPORTS.RPT.DEFICIENT_ACCOUNTS

/****** Object:  Table CBDB_REPORTS.RPT.DEFICIENT_ACCOUNTS    Script Date: 10/12/2019 4:15:56 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE CBDB_REPORTS.RPT.DEFICIENT_ACCOUNTS(
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[HEADER_ID] [bigint] NULL,
	[BUSINESS_DATE] [date] NULL,
	[ACCOUNT_NO] [nvarchar](30) NULL,
	[CODE] smallint null,
	[BALANCE] [numeric](18,2) NULL,
	[LOAN_BALANCE] [numeric](18,2) NULL,
	[DATE_CREATED] [date] NULL
) ON [PRIMARY]
GO


