DROP VIEW IF EXISTS [dbo].[VW_UnpostedRem]

/****** Object:  View [dbo].[VW_UnpostedRem]    Script Date: 11/12/2019 11:41:22 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE VIEW [dbo].[VW_UnpostedRem] AS

SELECT
D.CIF_NO,
C.FULL_NAME 'NAME',
B.EMPLOYEE_NO,
B.PRODUCT_NAME 'LOAN TYPE',	
A.AMOUNT 'REMIT AMOUNT',
A.UNPOSTED_REASON,	
B.PRINCIPAL_BALANCE,
B.INTEREST_BALANCE,
B.LOAN_BALANCE,
B.AIR_BALANCE

FROM LMS.REMITTANCE				A
LEFT JOIN LMS.ACCOUNT_MASTER	B WITH(NOLOCK) ON A.ACCOUNT_NO = B.ACCOUNT_NO
LEFT JOIN CMN.BILLING			D WITH(NOLOCK) ON A.ACCOUNT_NO = D.ACCOUNT_NO
LEFT JOIN MMS.CLIENT			C WITH(NOLOCK) ON D.CIF_NO = C.MEMBER_NO

GO


