IF COL_LENGTH('CBDB_REPORTS.LMS.COLLATERAL', 'COLLATERAL_TYPE_DESC') IS NULL
BEGIN
	ALTER TABLE CBDB_REPORTS.LMS.COLLATERAL
	ADD COLLATERAL_TYPE_DESC VARCHAR(20)
END

IF COL_LENGTH('CBDB_REPORTS.LMS.COLLATERAL', 'COLLATERAL_ID') IS NULL
BEGIN
	ALTER TABLE CBDB_REPORTS.LMS.COLLATERAL
	ADD COLLATERAL_ID VARCHAR(20)
END