DROP TABLE IF EXISTS CBDB_REPORTS.MMS.MEMBER_SPA_GAR

/****** Object:  Table [MMS].[MEMBER_SPA_GAR]    Script Date: 03/12/2019 4:34:35 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE CBDB_REPORTS.MMS.MEMBER_SPA_GAR(
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[HEADER_ID] [bigint] NOT NULL,
	[MEMBER_NO] [nvarchar](15) NOT NULL,
	[TYPE] [smallint] NULL,
	[TAG] [smallint] NULL,
	[MEMBER_SPA_GAR_GUID] [nvarchar](36) NOT NULL,
	[START_DATE] datetime NULL,
	[END_DATE] datetime NULL,
	[STATUS] [smallint] NULL,
	[COVERAGE] [nvarchar](10) NULL,
	[COVERAGE_VALUE] [nvarchar](60) NULL,
	[COVERAGE_DESC] [nvarchar](100) NULL,
	[LAST_UPDATED_DATE] DATETIME NULL)
GO


