DROP TABLE IF EXISTS  CBDB_REPORTS.[MMS].[MEMBER_SPA_GAR_ATT]
/****** Object:  Table [MMS].[MEMBER_SPA_GAR_ATT]    Script Date: 03/12/2019 4:49:06 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE CBDB_REPORTS.[MMS].[MEMBER_SPA_GAR_ATT](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[HEADER_ID] [bigint] NOT NULL,
	[MEMBER_NO] [nvarchar](15) NOT NULL,
	[MEMBER_SPA_GAR_GUID] [nvarchar](36) NOT NULL,
	[FIRST_NAME] [nvarchar](60) NULL,
	[MIDDLE_NAME] [nvarchar](60) NULL,
	[LAST_NAME] [nvarchar](60) NULL,
	[SUFFIX_NAME] [nvarchar](30) NULL,
	[FULL_NAME] [nvarchar](180) NULL,
	[LAST_UPDATED_DATE] [datetime] NULL)

