DROP TABLE IF EXISTS [CBDB_REPORTS].[CMN].[BUSINESS_VARIABLE]
/****** Object:  Table [CBDB_COMMON_ADMIN].[BUSINESS_VARIABLE]    Script Date: 06/12/2019 3:15:10 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE[CBDB_REPORTS].[CMN].[BUSINESS_VARIABLE](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[HEADER_ID] BIGINT,
	[VARIABLE_CODE] [nvarchar](30) NULL,
	[VARIABLE_DESCRIPTION] [nvarchar](150) NULL,
	[VARIABLE_VALUE] [nvarchar](256) NULL,
	[VARIABLE_DATA_TYPE] [nvarchar](10) NULL,
	[IS_EDITABLE] [smallint] NULL,
	[LAST_UPDATED_DATE] [datetime] NULL,
	[LAST_UPDATED_BY] [nvarchar](20) NULL,
	[STATUS] [smallint] NULL)
GO
