IF COL_LENGTH('CBDB_REPORTS.MMS.CFG_CORP_CONTACT_PERSON', 'LANDLINE_CTY_CODE') IS NULL
BEGIN
	ALTER TABLE CBDB_REPORTS.MMS.CFG_CORP_CONTACT_PERSON
	ADD LANDLINE_CTY_CODE VARCHAR(30)
END

IF COL_LENGTH('CBDB_REPORTS.MMS.CFG_CORP_CONTACT_PERSON', 'LANDLINE_PREFIX') IS NULL
BEGIN
	ALTER TABLE CBDB_REPORTS.MMS.CFG_CORP_CONTACT_PERSON
	ADD LANDLINE_PREFIX VARCHAR(20)
END

IF COL_LENGTH('CBDB_REPORTS.MMS.CFG_CORP_CONTACT_PERSON', 'LANDLINE_NUMBER') IS NULL
BEGIN
	ALTER TABLE CBDB_REPORTS.MMS.CFG_CORP_CONTACT_PERSON
	ADD LANDLINE_NUMBER VARCHAR(60)
END


IF COL_LENGTH('CBDB_REPORTS.MMS.CFG_CORP_CONTACT_PERSON', 'LANDLINE_EXT') IS NULL
BEGIN
	ALTER TABLE CBDB_REPORTS.MMS.CFG_CORP_CONTACT_PERSON
	ADD LANDLINE_EXT VARCHAR(50)
END

