IF COL_LENGTH('CBDB_REPORTS.MMS.CLIENT', 'GROUP_CODE') IS NULL
BEGIN
	ALTER TABLE CBDB_REPORTS.MMS.CLIENT
	ADD GROUP_CODE VARCHAR(20)
END

IF COL_LENGTH('CBDB_REPORTS.MMS.CLIENT', 'GROUP_CODE_DESC') IS NULL
BEGIN
	ALTER TABLE CBDB_REPORTS.MMS.CLIENT
	ADD GROUP_CODE_DESC VARCHAR(250)
END

