--ADD TORI_TAG
IF COL_LENGTH('CBDB_REPORTS.MMS.CLIENT', 'TORI_TAG') IS NULL
BEGIN
	ALTER TABLE CBDB_REPORTS.MMS.CLIENT
	ADD TORI_TAG BIT 
END
--ADD TORI_TAG_LAST_UPDATED_DATE
IF COL_LENGTH('CBDB_REPORTS.MMS.CLIENT', 'TORI_TAG_LAST_UPDATED_DATE') IS NULL
BEGIN
	ALTER TABLE CBDB_REPORTS.MMS.CLIENT
	ADD TORI_TAG_LAST_UPDATED_DATE DATE
END