--ADD PROGRESS INDICATOR
IF COL_LENGTH('CBDB_REPORTS.CMN.DATA_COPY_HEADER', 'PROGRESS') IS NULL
BEGIN
	ALTER TABLE CBDB_REPORTS.CMN.DATA_COPY_HEADER
	ADD PROGRESS VARCHAR(10) DEFAULT '0%' NOT NULL
END