--ADD PREV_CORp_NAME
IF COL_LENGTH('CBDB_REPORTS.MMS.CLIENT','PREV_CORP_NAME') IS NULL
BEGIN 
ALTER TABLE CBDB_REPORTS.MMS.CLIENT
ADD PREV_CORP_NAME VARCHAR(255)
END
--RENAME POSTION INTO POSITION
IF COL_LENGTH('CBDB_REPORTS.MMS.PEP_INFO','POSTION') IS NOT NULL
BEGIN 
 EXEC sp_rename  'CBDB_REPORTS.MMS.PEP_INFO.POSTION', 'POSITION', 'COLUMN';
END