IF COL_LENGTH('CBDB_REPORTS.CMN.BILLING', 'TRANSFERRED_TO_CO_MAKER') IS NULL
BEGIN
	ALTER TABLE CBDB_REPORTS.CMN.BILLING
	ADD TRANSFERRED_TO_CO_MAKER BIT DEFAULT 0 NOT NULL
END
GO

IF COL_LENGTH('CBDB_REPORTS.CMN.BILLING', 'ORIGINAL_BORROWER') IS NULL
BEGIN
	ALTER TABLE CBDB_REPORTS.CMN.BILLING
	ADD ORIGINAL_BORROWER VARCHAR(20) NULL
END
GO