DROP TABLE IF EXISTS dbo.CO_TRANSFER_HISTORY
DROP TABLE IF EXISTS CBDB_REPORTS.MMS.CO_TRANSFER_HISTORY

/****** Object:  Table [dbo].[CO_TRANSFER_HISTORY]    Script Date: 26/10/2019 2:20:47 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE CBDB_REPORTS.MMS.CO_TRANSFER_HISTORY(
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[HEADER_ID] [bigint] NOT NULL,
	[MEMBER_NO] [varchar](20) NOT NULL,
	[PREVIOUS_COMPANY] [nvarchar](60) NULL,
	[NEW_COMPANY] [nvarchar](60) NULL,
	[DATE] [date] NULL,
	[REASON] [nvarchar](100) NULL,
	[LAST_UPDATED_BY] [nvarchar](20) NULL,
	[LAST_APPROVED_BY] [nvarchar](20) NULL,
	[LAST_MAINTAINED_BRANCH] [varchar](10) NULL
) ON [PRIMARY]
GO


