DROP TABLE IF EXISTS CBDB_REPORTS.LMS.ACCOUNT_CO_MAKER

/****** Object:  Table [LMS].[ACCOUNT_CO_MAKER]    Script Date: 24/10/2019 4:19:33 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE CBDB_REPORTS.LMS.ACCOUNT_CO_MAKER(
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[HEADER_ID] [bigint] NOT NULL,
	[ACCOUNT_NO] [nchar](18) NOT NULL,
	[CIF_NO] [nvarchar](30) NOT NULL,
	[BILL_ALLOWED] [smallint] NULL,
	[STATUS] [varchar](255) NULL,
	[BILL_TRANSFER_DATE] [date] NULL,
 CONSTRAINT [PK_CO_MAKER] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)
)