IF COL_LENGTH('CBDB_REPORTS.LMS.ACCOUNT_MASTER', 'WRITE_OFF_BOARD_RES_NO') IS NULL
BEGIN
	ALTER TABLE CBDB_REPORTS.LMS.ACCOUNT_MASTER
	ADD WRITE_OFF_BOARD_RES_NO BIGINT NULL
END
GO

IF COL_LENGTH('CBDB_REPORTS.LMS.ACCOUNT_MASTER', 'WRITE_OFF_BOARD_APP_DATE') IS NULL
BEGIN
	ALTER TABLE CBDB_REPORTS.LMS.ACCOUNT_MASTER
	ADD WRITE_OFF_BOARD_APP_DATE DATE NULL
END
GO

IF COL_LENGTH('CBDB_REPORTS.LMS.ACCOUNT_MASTER', 'BOARD_RES_NO') IS NULL
BEGIN
	ALTER TABLE CBDB_REPORTS.LMS.ACCOUNT_MASTER
	ADD BOARD_RES_NO BIGINT NULL
END
GO

IF COL_LENGTH('CBDB_REPORTS.LMS.ACCOUNT_MASTER', 'BOARD_APP_DATE') IS NULL
BEGIN
	ALTER TABLE CBDB_REPORTS.LMS.ACCOUNT_MASTER
	ADD BOARD_APP_DATE DATE NULL
END
GO
