--ADD ATTORNEY FOR SPA
IF COL_LENGTH('CBDB_REPORTS.MMS.CLIENT', 'SPA_ATTORNEY') IS NULL
BEGIN
	ALTER TABLE CBDB_REPORTS.MMS.CLIENT
	ADD SPA_ATTORNEY VARCHAR(100) 
END
--ADD ATTORNEY FOR GARNISH
IF COL_LENGTH('CBDB_REPORTS.MMS.CLIENT', 'GAR_ATTORNEY') IS NULL
BEGIN
	ALTER TABLE CBDB_REPORTS.MMS.CLIENT
	ADD GAR_ATTORNEY VARCHAR(100) 
END

