DROP TABLE IF EXISTS CBDB_REPORTS.MMS.CFG_CORP_CONTACT_PERSON
/****** Object:  Table [MMS].[CFG_CORPORATE_CONTACT_PERSON]    Script Date: 23/10/2019 11:17:09 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE CBDB_REPORTS.MMS.CFG_CORP_CONTACT_PERSON(
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[HEADER_ID] [bigint] NOT NULL,
	[CONTACT_PERSON_GUID] [nvarchar](36) NULL,
	[CORPORATE_CODE] [nvarchar](8) NOT NULL,
	[FIRST_NAME] [nvarchar](60) NOT NULL,
	[MIDDLE_NAME] [nvarchar](60) NOT NULL,
	[LAST_NAME] [nvarchar](60) NOT NULL,
	[SUFFIX_NAME] [nvarchar](30) NULL,
	[DESIGNATION] [nvarchar](100) NOT NULL,
	[DEPARTMENT] [nvarchar](100) NOT NULL,
	[RELATED_CIF_NO] [nvarchar](15) NULL,
	[ADDRESS_GUID] [nvarchar](36) NULL,
	[CONTACT_GUID] [nvarchar](36) NULL,
 CONSTRAINT [CFG_CORPORATE_CONTACT_PERSON_PK] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

