ALTER TABLE CBDB_REPORTS.LMS.ACCT_BAL_HISTORY
	DROP COLUMN IF EXISTS OR_AR_NO
GO


IF COL_LENGTH('CBDB_REPORTS.LMS.ACCT_BAL_HISTORY', 'OR_NO') IS NULL
BEGIN
	ALTER TABLE CBDB_REPORTS.LMS.ACCT_BAL_HISTORY
	ADD OR_NO VARCHAR(60)
END


IF COL_LENGTH('CBDB_REPORTS.LMS.ACCT_BAL_HISTORY', 'AR_NO') IS NULL
BEGIN
	ALTER TABLE CBDB_REPORTS.LMS.ACCT_BAL_HISTORY
	ADD AR_NO VARCHAR(60)
END
