DROP VIEW IF EXISTS [dbo].[VW_DormantAcct]
GO

/****** Object:  View [dbo].[VW_DormantAcct]    Script Date: 01/10/2020 10:20:36 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO




CREATE VIEW [dbo].[VW_DormantAcct] AS
SELECT
A.ACCOUNT_NO,
A.MEMBER_NO,
B.LAST_NAME,
B.FIRST_NAME,
B.MIDDLE_NAME,
B.CORP_CODE,
B.MEMBER_TYPE,
B.MEMBER_CLASS,
B.STATUS,
A.LAST_FIN_TXN_DATE,
A.LEDGER_BAL

FROM DMS.ACCOUNT_MASTER				A WITH (NOLOCK)
LEFT JOIN MMS.CLIENT				B WITH (NOLOCK) ON B.MEMBER_NO = A.MEMBER_NO
WHERE A.PRODUCT_CODE != '001'		--NOT CCA
	AND A.IS_CLOSE = 0
	AND A.ACCOUNT_STATUS_CODE='02'	--DORMANT STATUS
GO


