DROP TABLE IF EXISTS [COLT].[APPRAISAL]
DROP TABLE IF EXISTS CBDB_REPORTS.LMS.APPRAISAL

/****** Object:  Table [COLT].[APPRAISAL]    Script Date: 29/10/2019 1:23:49 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE CBDB_REPORTS.LMS.APPRAISAL(
	[ID] [bigint] NOT NULL,
	[HEADER_ID] [bigint] NOT NULL,
	[COLLATERAL_ID] [nchar](17) NOT NULL,
	[ACCOUNT_NO] [varchar](20) NULL,
	[NAME] [nvarchar](180) NOT NULL,
	[APPRAISAL_DATE] [date] NOT NULL,
	[APPRAISED_VALUE] [numeric](15, 2) NOT NULL,
	[REPA_NO] [nvarchar](20) NULL,
	[APPRAISER_FEE] [numeric](15, 2) NULL,
	[ACKNOWLEDGE_RECEIPT] [nvarchar](20) NULL,
	[ACKNOWLEDGE_RECEIPT_DATE] [date] NULL,
	[REMARKS] [nvarchar](100) NULL,
	[NEXT_APPRAISAL_DATE] [date] NULL,
	[ENCODED_DATE] [date] NULL,
	[RECEIVED_DATE] [date] NULL,
	[DELIVERED_DATE] [date] NULL,
	[APPRAISAL_REF_NO] [nvarchar](8) NULL,
	[USER_ID] [nvarchar](50) NULL,
	[PAYMENT_DATE] [date] NULL,
	[FEE_PAID] [decimal](18, 2) NULL,
	[BILLING_DATE] [date] NULL,
	[BILLING_AMOUNT] [decimal](18, 2) NULL,
	[TCT_NO] [nvarchar](50) NULL
) ON [PRIMARY]
GO


