--DROP COMPLETION_AMOUNT IN CLIENT AS WELL AS THE CONSTRAINT
DECLARE @CONSTR VARCHAR(MAX) = (SELECT TOP 1 NAME FROM cbdb_reports.sys.default_constraints WHERE [name] LIKE 'DF__CLIENT__COMPLETI%')
IF EXISTS (SELECT 1 FROM cbdb_reports.sys.default_constraints WHERE [name] LIKE 'DF__CLIENT__COMPLETI%')
BEGIN
  EXEC('ALTER TABLE cbdb_reports.[MMS].[CLIENT] DROP CONSTRAINT ' +  @CONSTR)
  IF COL_LENGTH('CBDB_REPORTS.MMS.CLIENT', 'COMPLETION_AMOUNT') IS NOT NULL
	BEGIN
		ALTER TABLE CBDB_REPORTS.MMS.CLIENT 
		DROP COLUMN COMPLETION_AMOUNT 
	END
END

--ADD COMPLETION_AMOUNT TO DMS.ACCOUNT_MASTER
IF COL_LENGTH('CBDB_REPORTS.DMS.ACCOUNT_MASTER', 'COMPLETION_AMOUNT') IS NULL
BEGIN
	ALTER TABLE CBDB_REPORTS.DMS.ACCOUNT_MASTER 
	ADD COMPLETION_AMOUNT NUMERIC(18,2) DEFAULT 0
END

