DROP TABLE IF EXISTS [CBDB_REPORTS].[MMS].[FAMILY_GROUP]

/****** Object:  Table [MMS].[FAMILY_GROUP]    Script Date: 13/11/2019 3:08:24 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [MMS].[FAMILY_GROUP](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[HEADER_ID] [bigint] NOT NULL,
	[FAMILY_GROUP] [int],
	[COMPANY_NAME] [varchar](20),
	[PRIMARY_MEMBER_NO] [varchar](20),
	[PRIMARY_MEMBER_NAME] [varchar](200),
	[PRIMARY_MEMBER_STATUS] [varchar](20),
	[PRIMARY_MEMBERSHIP_DATE] [date],
	[SEC_MEMBER_NO] [varchar](20),
	[SEC_MEMBER_NAME] [varchar](200),
	[SEC_MEMBER_STATUS] [varchar](20),
	[SEC_MEMBERSHIP_DATE] [date],
	[RELATIONSHIP_TO_PRIMARY] [varchar](200)
)
GO