IF COL_LENGTH('CBDB_REPORTS.RPT.CDTR_REF_DETAILS', 'PRODUCT_NAME') IS NULL
BEGIN
	ALTER TABLE CBDB_REPORTS.RPT.CDTR_REF_DETAILS
	ADD PRODUCT_NAME VARCHAR(100)
END

IF COL_LENGTH('CBDB_REPORTS.RPT.CDTR_REF_DETAILS', 'PRODUCT_MNEMONIC') IS NULL
BEGIN
	ALTER TABLE CBDB_REPORTS.RPT.CDTR_REF_DETAILS
	ADD PRODUCT_MNEMONIC VARCHAR(30)
END
