DROP TABLE IF EXISTS  CBDB_REPORTS.CMN.CFG_INSURANCE_TYPE
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE CBDB_REPORTS.CMN.CFG_INSURANCE_TYPE(
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[INSURANCE_TYPE] [varchar](10) NOT NULL,
	[INSURANCE_DESCRIPTION] [varchar](150) NOT NULL,
)

