IF COL_LENGTH('CBDB_REPORTS.DMS.ACCOUNT_BAL_HISTORY', 'HOST_ID') IS NULL
BEGIN
	ALTER TABLE CBDB_REPORTS.DMS.ACCOUNT_BAL_HISTORY
	ADD HOST_ID BIGINT
END

IF COL_LENGTH('CBDB_REPORTS.LMS.ACCT_BAL_HISTORY', 'HOST_ID') IS NULL
BEGIN
	ALTER TABLE CBDB_REPORTS.LMS.ACCT_BAL_HISTORY
	ADD HOST_ID BIGINT
END

