UPDATE CBDB_REPORTS.RPT.REPORT_GENERATOR
SET DIRECTORY = 'AD HOC\WORD\TORILoanA.mrt',
	EXPORT_TYPE = 'WORD'
WHERE FILE_NAME = 'TORILoanA'

UPDATE CBDB_REPORTS.RPT.REPORT_GENERATOR
SET DIRECTORY = 'AD HOC\WORD\TORILoanB.mrt',
	EXPORT_TYPE = 'WORD'
WHERE FILE_NAME = 'TORILoanB'

UPDATE CBDB_REPORTS.RPT.REPORT_GENERATOR
SET DIRECTORY = 'AD HOC\WORD\TORILoanC.mrt',
	EXPORT_TYPE = 'WORD'
WHERE FILE_NAME = 'TORILoanC'

UPDATE CBDB_REPORTS.RPT.REPORT_GENERATOR
SET DIRECTORY = 'AD HOC\WORD\TORILoanD.mrt',
	EXPORT_TYPE = 'WORD'
WHERE FILE_NAME = 'TORILoanD'