IF NOT EXISTS (SELECT 1 FROM CBDB_REPORTS.CMN.CFG_INSURANCE_TYPE)
BEGIN
	INSERT INTO CBDB_REPORTS.CMN.CFG_INSURANCE_TYPE(INSURANCE_TYPE, INSURANCE_DESCRIPTION) VALUES ('1','OR')
	INSERT INTO CBDB_REPORTS.CMN.CFG_INSURANCE_TYPE(INSURANCE_TYPE, INSURANCE_DESCRIPTION) VALUES ('2','MRI')
	INSERT INTO CBDB_REPORTS.CMN.CFG_INSURANCE_TYPE(INSURANCE_TYPE, INSURANCE_DESCRIPTION) VALUES ('3','Car Insurance')
	INSERT INTO CBDB_REPORTS.CMN.CFG_INSURANCE_TYPE(INSURANCE_TYPE, INSURANCE_DESCRIPTION) VALUES ('4','Fire Insurance')
	INSERT INTO CBDB_REPORTS.CMN.CFG_INSURANCE_TYPE(INSURANCE_TYPE, INSURANCE_DESCRIPTION) VALUES ('5','Real Property Tax')
END
