DROP VIEW IF EXISTS [dbo].[VW_ATMWdwlSum]

/****** Object:  View [dbo].[VW_ATMWdwlSum] Script Date: 12/11/2019 4:35:19 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[VW_ATMWdwlSum] AS 
SELECT	ACM.PRODUCT_MNE + '-' + (CASE ABH.TRAN_CODE WHEN '3761' THEN 'BDO' WHEN '3762' THEN 'BPI' END) AS 'WITHDRAWAL'
	   ,ABH.TRAN_CODE
	   ,COUNT(1) AS [COUNT]
	   ,SUM(ISNULL(ABH.AMOUNT,0)) AS AMOUNT 
FROM	  CBDB_REPORTS.DMS.ACCOUNT_BAL_HISTORY ABH WITH(NOLOCK)
LEFT JOIN CBDB_REPORTS.DMS.ACCOUNT_MASTER      ACM WITH(NOLOCK)
ON		  ABH.ACCOUNT_NO = ACM.ACCOUNT_NO
WHERE  DATEDIFF(MONTH,ABH.TRAN_DATE, (SELECT CURRENT_BUSINESS_DATE FROM CBDB_REPORTS.CMN.BANK_SUNDRY)) = 0   
AND    ABH.IS_REVERSAL = 0
AND    (SELECT COUNT(*) FROM CBDB_REPORTS.DMS.ACCOUNT_BAL_HISTORY A WITH(NOLOCK) WHERE A.ACCOUNT_NO = ABH.ACCOUNT_NO 
       AND A.REVERSAL_ID=ABH.HOST_ID AND A.IS_REVERSAL=1) = 0
AND    ABH.TRAN_CODE IN ('3761', --BDO
					     '3762') --BPI
AND    ACM.PRODUCT_CODE <> '003' --EXCEPT TIME DEPOSIT
GROUP BY ACM.PRODUCT_MNE, ABH.TRAN_CODE

GO