USE CBDB_STAGE
GO

DROP PROCEDURE IF EXISTS dbo.FILL_BANK_DETAILS

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE dbo.FILL_BANK_DETAILS
	@HEADER_ID BIGINT,
	@BUSINESS_DATE DATE,
	@IS_COMPLETED INT = 0,
	@SP_NAME NVARCHAR(50) = 'FILL_RPT_BANK_DETAILS',
	@TABLE_NAME NVARCHAR(100) = 'RPT.BANK_DETAILS',
	@INSERTED_RECORDS BIGINT = 0,
	@ERR_MSG NVARCHAR(500) = '',
	@DURATION BIGINT = 0
AS
BEGIN
	--CHECK STATUS IF COMPLETED
	SET @IS_COMPLETED = ISNULL((SELECT TOP 1 [STATUS] FROM CBDB_REPORTS.RPT.SP_LOG WITH(NOLOCK) WHERE BUSINESS_DATE = @BUSINESS_DATE AND HEADER_ID = @HEADER_ID AND NAME = @SP_NAME ORDER BY ID DESC),0)
	
	--LOGGED IF PROCESS ALREADY COMPLETED
	IF (@IS_COMPLETED = 4) BEGIN  PRINT @SP_NAME + ' IS ALREADY COMPLETED.' END
	IF @IS_COMPLETED <> 4
	BEGIN
		--IF TABLE HAS ERROR PREVIOUSLY, DELETE ALL RECORDS FROM TABLE WITH CURRENT HEADER_ID	
		IF @IS_COMPLETED = 3
		BEGIN
			EXEC ('DELETE FROM CBDB_REPORTS.' + @TABLE_NAME + ' WHERE HEADER_ID = ' + @HEADER_ID +' AND BUSINESS_DATE=' + ''''+ @BUSINESS_DATE + ''''+'')
		END

		--AUTO DUMP TABLE
		BEGIN
			EXEC ('TRUNCATE TABLE CBDB_REPORTS.' + @TABLE_NAME)
		END

		--LOG START
		BEGIN
			INSERT INTO CBDB_REPORTS.RPT.SP_LOG (HEADER_ID  ,NAME	  ,BUSINESS_DATE  ,TIME_STARTED ,STATUS)
									VALUES		(@HEADER_ID ,@SP_NAME ,@BUSINESS_DATE ,GETDATE()    ,1)
			PRINT '---------------------------------------------------------------------------------------------------------------------------------------------------------------------------'
			PRINT 'STATUS : STARTED   | PROCEDURE NAME : ' + @SP_NAME + ' | HEADER_ID : ' + CAST(@HEADER_ID AS VARCHAR(MAX)) + ' | TIME STARTED : ' + CAST(GETDATE() AS VARCHAR(MAX)) + ' | BUSINESS DATE : ' + CAST(@BUSINESS_DATE AS VARCHAR(MAX))			
		END

		BEGIN TRY
			SELECT @INSERTED_RECORDS = 0						  
			BEGIN
			--->INSERT INTO SELECT STATEMENT
				INSERT INTO CBDB_REPORTS.RPT.BANK_DETAILS WITH(TABLOCK) 
						   (HEADER_ID, BANK_NAME, BANK_SHORT_NAME, BANK_ADDRESS)
			       SELECT  @HEADER_ID, A.BANK_NAME,	 B.BANK_SHORT_NAME,	   C.BANK_ADDRESS 
				   FROM
				   		  (SELECT VARIABLE_VALUE 'BANK_NAME' FROM CBDB_REPORTS.CMN.BUSINESS_VARIABLE WITH(NOLOCK) WHERE VARIABLE_CODE = 'RPT_BANK_NAME')A,
				   		  (SELECT VARIABLE_VALUE 'BANK_SHORT_NAME' FROM CBDB_REPORTS.CMN.BUSINESS_VARIABLE WITH(NOLOCK) WHERE VARIABLE_CODE = 'RPT_BANK_SHORT_NAME')B,
				   		  (SELECT VARIABLE_VALUE 'BANK_ADDRESS' FROM CBDB_REPORTS.CMN.BUSINESS_VARIABLE WITH(NOLOCK) WHERE VARIABLE_CODE = 'RPT_BANK_ADDRESS')C				 
			--->END OF INSERT INTO SELECT STATEMENT		
				SET @INSERTED_RECORDS = @INSERTED_RECORDS + @@ROWCOUNT
			END
		END TRY
		BEGIN CATCH
			SET @ERR_MSG = ERROR_MESSAGE()
			INSERT INTO CBDB_REPORTS.RPT.ERROR_DETAILS ([ERROR_NUMBER],[ERROR_SEVERITY],[ERROR_STATE],[ERROR_LINE],[ERROR_MESSAGE],[ERROR_TABLE],[TRANCOUNT],[REMARKS],[DATE_OCCURED])
			VALUES (ERROR_NUMBER(), ERROR_SEVERITY(), ERROR_STATE(),ERROR_LINE(),ERROR_MESSAGE(),@TABLE_NAME, CONVERT(varchar, @@TRANCOUNT),'',GETDATE());
			--LOG AFTER ERROR
			UPDATE CBDB_REPORTS.RPT.SP_LOG
				SET STATUS = 3
			WHERE HEADER_ID = @HEADER_ID AND BUSINESS_DATE = @BUSINESS_DATE
			PRINT '---------------------------------------------------------------------------------------------------------------------------------------------------------------------------'
			PRINT 'STATUS : FAILED     | PROCEDURE NAME : ' + @SP_NAME + ' | HEADER_ID : ' + CAST(@HEADER_ID AS VARCHAR(MAX)) + ' | BUSINESS DATE : ' + CAST(@BUSINESS_DATE AS VARCHAR(MAX)) + ' | ERROR MESSAGE : ' + @ERR_MSG
			PRINT '---------------------------------------------------------------------------------------------------------------------------------------------------------------------------'
		END CATCH

		--LOG FINISH IF THE TABLE HAS NO ERROR 
		IF @ERR_MSG IS NULL OR @ERR_MSG = ''
		BEGIN
			SET @DURATION = DATEDIFF(SECOND, (SELECT TOP 1 TIME_STARTED FROM CBDB_REPORTS.RPT.SP_LOG WHERE HEADER_ID = @HEADER_ID AND BUSINESS_DATE = @BUSINESS_DATE ORDER BY ID DESC), GETDATE())		
			UPDATE CBDB_REPORTS.RPT.SP_LOG
				SET STATUS	   = 4,
					TIME_ENDED = GETDATE(),
					DURATION   = @DURATION,
					INSERTED_RECORDS = @INSERTED_RECORDS
			WHERE HEADER_ID = @HEADER_ID AND BUSINESS_DATE = @BUSINESS_DATE  AND NAME = @SP_NAME
			PRINT 'STATUS : COMPLETED | PROCEDURE NAME : ' + @SP_NAME + ' | HEADER_ID : ' + CAST(@HEADER_ID AS VARCHAR(MAX)) + ' | RECORD COUNT : ' + CAST(@INSERTED_RECORDS AS VARCHAR(MAX)) + ' | TIME ENDED : ' + CAST(GETDATE() AS VARCHAR(MAX)) + ' | DURATION : ' + CONVERT(VARCHAR(50),@DURATION)			       
			PRINT '---------------------------------------------------------------------------------------------------------------------------------------------------------------------------'
		END
	END
END