USE CBDB_STAGE
DROP PROCEDURE IF EXISTS [dbo].[LOG_DETAILS]
/****** Object:  StoredProcedure [dbo].[LOG_DETAILS]    Script Date: 14/10/2019 5:39:55 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_WARNINGS OFF 
GO 
CREATE PROCEDURE [dbo].[LOG_DETAILS]
	@COPY_HEADER_ID BIGINT = 0,
	@COPY_DETAIL_ID BIGINT = 0,
	@TABLE_NAME VARCHAR(100),
	@BUS_DATE DATE,
	@RECORD_COUNT INT = 0,
	@FAIL_EXCEPTION VARCHAR(255) = '',
	@STATUS INT = 0,
	@SCHEMA_NAME VARCHAR(10) = '',
	@MODULE_CODE VARCHAR(50) = '',
	@IS_DUMP BIT = 0,
	@STAGE_TABLE_NAME VARCHAR(100) = ''
AS
	BEGIN
		DECLARE @TIME_STARTED DATETIME, @TIME_ENDED DATETIME

		DECLARE @TABLE_COUNT INT = (CASE @SCHEMA_NAME WHEN 'CMN'
									THEN ISNULL((SELECT COUNT(TABLE_NAME) FROM CBDB_REPORTS.INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = @SCHEMA_NAME),0) - 4
								    WHEN 'MMS'
									THEN ISNULL((SELECT COUNT(TABLE_NAME) FROM CBDB_REPORTS.INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = @SCHEMA_NAME),0) - 1								
									ELSE ISNULL((SELECT COUNT(TABLE_NAME) FROM CBDB_REPORTS.INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = @SCHEMA_NAME),0)
									END)
		DECLARE @TABLES_SUCCEEDED INT = ISNULL((SELECT COUNT(1) FROM CBDB_REPORTS.CMN.DATA_COPY_DETAIL WITH(NOLOCK) WHERE STATUS = 4 AND HEADER_ID = @COPY_HEADER_ID),0)
		DECLARE @TOTAL_DUMP_RECORD INT = ISNULL((SELECT SUM(ISNULL(RECORD_COUNT,0)) FROM CBDB_REPORTS.CMN.DATA_COPY_DETAIL WITH(NOLOCK) WHERE HEADER_ID = @COPY_HEADER_ID AND IS_DUMP = 1),0)
		DECLARE @TOTAL_DELTA_RECORD INT =ISNULL((SELECT SUM(ISNULL(RECORD_COUNT,0)) FROM CBDB_REPORTS.CMN.DATA_COPY_DETAIL WITH(NOLOCK) WHERE HEADER_ID = @COPY_HEADER_ID AND IS_DUMP <> 1),0)
		DECLARE @TABLE_WITH_ERROR INT = ISNULL((SELECT COUNT(1) FROM CBDB_REPORTS.CMN.DATA_COPY_DETAIL WITH(NOLOCK) WHERE [STATUS] = 3 AND HEADER_ID = @COPY_HEADER_ID),0)
		DECLARE @TOTAL_DURATION INT = ISNULL((SELECT SUM(ISNULL(DURATION,0)) FROM CBDB_REPORTS.CMN.DATA_COPY_DETAIL WHERE HEADER_ID = @COPY_HEADER_ID),0)
		DECLARE @PROGRESS VARCHAR(30)

		IF (@TABLE_COUNT > 0)
		BEGIN
			SET @PROGRESS = CAST(CAST(((CAST(@TABLES_SUCCEEDED + 1 AS DECIMAL(18,2)) / CAST(@TABLE_COUNT AS DECIMAL(18,2))) * 100) AS DECIMAL(18,2)) AS VARCHAR(30)) + '%' --SET PROGRESS OF THE HEADER
		END

		--STARTED
		IF @STATUS = 1
		BEGIN
			IF NOT EXISTS (SELECT 1 FROM CBDB_REPORTS.CMN.DATA_COPY_DETAIL WITH(NOLOCK) WHERE TABLE_NAME = @TABLE_NAME AND HEADER_ID = @COPY_HEADER_ID)
			BEGIN				
				INSERT INTO CBDB_REPORTS.CMN.DATA_COPY_DETAIL WITH(TABLOCK) (HEADER_ID, TABLE_NAME, BUSINESS_DATE, RECORD_COUNT, TIME_STARTED, [STATUS], IS_DUMP)
				VALUES (@COPY_HEADER_ID, @TABLE_NAME, @BUS_DATE, 0, GETDATE(), 1, @IS_DUMP)
				PRINT '---------------------------------------------------------------------------------------------------------------------------------------------------------------------------'
				PRINT 'STATUS : STARTED   | TABLE NAME : ' + @TABLE_NAME + ' | COPY_HEADER_ID : ' + CAST(@COPY_HEADER_ID AS VARCHAR(MAX)) + ' | IS DUMP? : ' + CAST(@IS_DUMP AS VARCHAR(1)) + ' | TIME STARTED : ' + CAST(GETDATE() AS VARCHAR(MAX))		
			END
			IF EXISTS(SELECT 1 STATUS FROM CBDB_REPORTS.CMN.DATA_COPY_DETAIL WITH(NOLOCK) WHERE TABLE_NAME = @TABLE_NAME AND HEADER_ID = @COPY_HEADER_ID AND STATUS = 3) --IF THE TABLE HAS ERROR PREVIOUSLLY, RE-RUN IT
			BEGIN
				UPDATE CBDB_REPORTS.CMN.DATA_COPY_DETAIL WITH(TABLOCK)
					SET TIME_STARTED = GETDATE(),
						IS_DUMP = @IS_DUMP		
				WHERE HEADER_ID = @COPY_HEADER_ID AND TABLE_NAME = @TABLE_NAME
				PRINT '---------------------------------------------------------------------------------------------------------------------------------------------------------------------------'
				PRINT 'STATUS : RE-RUNNING   | TABLE NAME : ' + @TABLE_NAME + ' | COPY_HEADER_ID : ' + CAST(@COPY_HEADER_ID AS VARCHAR(MAX)) + ' | IS DUMP? : ' + CAST(@IS_DUMP AS VARCHAR(1)) + ' | TIME STARTED : ' + CAST(GETDATE() AS VARCHAR(MAX))
			END
		END

		--FINISHED
		IF @STATUS = 4 --AND ((SELECT TOP 1 [STATUS] FROM CBDB_REPORTS.CMN.DATA_COPY_DETAIL WHERE ID = @COPY_DETAIL_ID) <> 3)
		BEGIN	
			IF EXISTS (SELECT TOP 1 IS_FAILED FROM CBDB_STAGE.CMN.DATA_COPY_DETAIL WHERE HEADER_ID = @COPY_HEADER_ID AND TABLE_NAME = @STAGE_TABLE_NAME AND IS_FAILED = 1 AND SCHEMA_NAME = @SCHEMA_NAME ORDER BY ID DESC)
			BEGIN
				SET @STATUS = 3 --SET TO 3 DUE TO FAILED STAGING
				SET @FAIL_EXCEPTION = @TABLE_NAME +' encountered an error in staging process.'
			END
			ELSE
			BEGIN
				SET @TIME_STARTED = (SELECT TIME_STARTED FROM CBDB_REPORTS.CMN.DATA_COPY_DETAIL WITH(NOLOCK) WHERE ID = @COPY_DETAIL_ID)
				UPDATE CBDB_REPORTS.CMN.DATA_COPY_DETAIL WITH(TABLOCK)
					SET RECORD_COUNT = @RECORD_COUNT,
						TIME_ENDED = GETDATE(),
						DURATION = DATEDIFF(SECOND, @TIME_STARTED, GETDATE()),
						STATUS = 4,
						FAIL_EXCEPTION = NULL
				WHERE ID = @COPY_DETAIL_ID
				PRINT 'STATUS : COMPLETED | TABLE NAME : ' + @TABLE_NAME + ' | COPY_HEADER_ID : ' + CAST(@COPY_HEADER_ID AS VARCHAR(MAX)) + ' | RECORD COUNT : ' + CAST(@RECORD_COUNT AS VARCHAR(MAX)) + ' | TIME ENDED : ' + CAST(GETDATE() AS VARCHAR(MAX)) + ' | DURATION : ' + CONVERT(VARCHAR(50),DATEDIFF(SECOND, @TIME_STARTED, GETDATE())) + ' | MODULE : ' + @MODULE_CODE + '(' + @PROGRESS + ')'			       
				PRINT '---------------------------------------------------------------------------------------------------------------------------------------------------------------------------'							
			END
		END

		--HAS ERROR
		IF @STATUS = 3
		BEGIN
			SET @TIME_STARTED = (SELECT TIME_STARTED FROM CBDB_REPORTS.CMN.DATA_COPY_DETAIL WITH(NOLOCK) WHERE ID = @COPY_DETAIL_ID)
			UPDATE CBDB_REPORTS.CMN.DATA_COPY_DETAIL WITH(TABLOCK)
				SET TIME_ENDED = GETDATE(),
					DURATION = DATEDIFF(SECOND, @TIME_STARTED, GETDATE()),
					STATUS = 3,
					FAIL_EXCEPTION = @FAIL_EXCEPTION
			WHERE ID = @COPY_DETAIL_ID
			PRINT 'STATUS : FAILED     | TABLE NAME : ' + @TABLE_NAME + ' | ERROR MESSAGE : ' + @FAIL_EXCEPTION + ' | TIME : ' + CAST(GETDATE() AS VARCHAR(MAX))
			PRINT '---------------------------------------------------------------------------------------------------------------------------------------------------------------------------'		
		END	
		BEGIN
			SET @TOTAL_DUMP_RECORD = ISNULL((SELECT SUM(ISNULL(RECORD_COUNT,0)) FROM CBDB_REPORTS.CMN.DATA_COPY_DETAIL WITH(NOLOCK) WHERE HEADER_ID = @COPY_HEADER_ID AND IS_DUMP = 1),0)
			SET @TOTAL_DELTA_RECORD =ISNULL((SELECT SUM(ISNULL(RECORD_COUNT,0)) FROM CBDB_REPORTS.CMN.DATA_COPY_DETAIL WITH(NOLOCK) WHERE HEADER_ID = @COPY_HEADER_ID AND IS_DUMP <> 1),0)
			SET @TABLE_WITH_ERROR = ISNULL((SELECT COUNT(1) FROM CBDB_REPORTS.CMN.DATA_COPY_DETAIL WITH(NOLOCK) WHERE [STATUS] = 3 AND HEADER_ID = @COPY_HEADER_ID),0)
			SET @TOTAL_DURATION = ISNULL((SELECT SUM(ISNULL(DURATION,0)) FROM CBDB_REPORTS.CMN.DATA_COPY_DETAIL WHERE HEADER_ID = @COPY_HEADER_ID),0)

			--IF THE TABLES ARE NOT YET COMPLETED SET THE HEADER STATUS TO 2
			IF @TABLE_COUNT > @TABLES_SUCCEEDED + 1
			BEGIN
				SET @STATUS = 2
			END				
			
			--IF ONE OF THE TABLES HAS AN ERROR SET THE HEADER STATUS TO 3
			SET @TABLE_WITH_ERROR = ISNULL((SELECT COUNT(1) FROM CBDB_REPORTS.CMN.DATA_COPY_DETAIL WITH(NOLOCK) WHERE [STATUS] = 3 AND HEADER_ID = @COPY_HEADER_ID),0)
			IF @TABLE_WITH_ERROR > 0
			BEGIN
				SET @STATUS = 3
			END	

			--UPDATE DATA COPY HEADER
			BEGIN
				UPDATE CBDB_REPORTS.CMN.DATA_COPY_HEADER WITH(TABLOCK)
					SET TIME_ENDED = GETDATE(),
						DURATION = @TOTAL_DURATION,
						TOTAL_DUMP_RECORD = @TOTAL_DUMP_RECORD,
						TOTAL_DELTA_RECORD = @TOTAL_DELTA_RECORD,
						STATUS = @STATUS,
						PROGRESS = @PROGRESS
				WHERE  ID = @COPY_HEADER_ID AND MODULE_CODE = @MODULE_CODE
			END			
		END	
	END
