--TRUNCATE TABLE CBDB_REPORTS.RPT.CDTR_REF_DETAILS

DECLARE 
@HEADER_ID BIGINT,
@SET_ID BIGINT = 0,
@BUSINESS_DATE DATE = '2019-11-04',
@TABLE_ACCT_BAL_HIST NVARCHAR(150) = 'DMS.ACCOUNT_BAL_HISTORY',
@INSERTED_RECORDS BIGINT = 0

IF NOT EXISTS (SELECT TOP 1 SET_ID FROM CBDB_REPORTS.RPT.CDTR_REF_DETAILS)
BEGIN
	SET @SET_ID = 1
	SET @HEADER_ID = (SELECT TOP 1 ID FROM CBDB_REPORTS.CMN.DATA_COPY_DETAIL WHERE TABLE_NAME = @TABLE_ACCT_BAL_HIST AND BUSINESS_DATE = @BUSINESS_DATE)
	INSERT INTO CBDB_REPORTS.RPT.CDTR_REF_DETAILS WITH(TABLOCK)
		   (HEADER_ID ,SET_ID ,BEGINNING_BALANCE						,ENDING_BALANCE ,ACCOUNT_TYPE ,TRANSACTION_DATE ,PRODUCT_NAME ,PRODUCT_MNEMONIC)
	SELECT @HEADER_ID ,@SET_ID,SUM(ISNULL(LEDGER_BAL,0)) AS 'LEDGER_BALANCE' ,0		    ,PRODUCT_CODE ,@BUSINESS_DATE   ,PRODUCT_DESC ,PRODUCT_MNE
	FROM CBDB_REPORTS.DMS.ACCOUNT_MASTER WITH(NOLOCK) GROUP BY PRODUCT_MNE ,PRODUCT_CODE,PRODUCT_DESC ,PRODUCT_MNE
END 

--SELECT * FROM CBDB_REPORTS.RPT.CDTR_REF_DETAILS
--DELETE FROM CBDB_REPORTS.RPT.CDTR_REF_DETAILS
SELECT * FROM CBDB_REPORTS.DMS.ACCOUNT_BAL_HISTORY