DROP VIEW IF EXISTS [dbo].[VW_BillingRep]

/****** Object:  View [dbo].[VW_BillingRep]    Script Date: 09/01/2020 9:55:39 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[VW_BillingRep] AS

SELECT
A.MAN_NO 'EMPLOYEE_NO',
CONCAT(A.LAST_NAME, + ',' + A.FIRST_NAME + ' ' + A.MIDDLE_NAME ) 'EMPLOYEE NAME',
A.COMP_CODE,
A.ACCOUNT_NO 'LOAN NO',
B.PRINCIPAL_AMOUNT,
B.RELEASED_DATE 'DATE GRANTED',
B.INTEREST_AMOUNT,
A.MONTHLY_AMORT,
B.TERM,
B.PRODUCT_NAME 'LOAN TYPE',
B.MATURITY_DATE,
B.ACCT_STATUS,
B.LOAN_AMOUNT

FROM CMN.BILLING A WITH(NOLOCK)
LEFT JOIN LMS.ACCOUNT_MASTER B WITH(NOLOCK) ON A.CIF_NO = B.MEMBER_NO

WHERE DATEDIFF(MONTH, A.LAST_UPDATED_DATE, (SELECT CURRENT_BUSINESS_DATE FROM CMN.BANK_SUNDRY)) = 0
AND IS_BILL_GENERATED = 1
GO
