DROP VIEW IF EXISTS [dbo].[VW_SSDMasterlist]

/****** Object:  View [dbo].[VW_SSDMasterlist]    Script Date: 10/01/2020 10:35:17 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE VIEW [dbo].[VW_SSDMasterlist] AS
SELECT 
A.ACCOUNT_NO, 
B.STATUS,
A.OLD_ACCT_NO AS 'SSD_NUMBER',
C.TRAN_CODE,
B.MEMBER_NO,
CASE WHEN B.MEMBER_TYPE_CODE = 'C'
	 THEN B.FULL_NAME
	 ELSE B.LAST_NAME
END AS LAST_NAME, 
B.FIRST_NAME, 
B.MIDDLE_NAME, 
B.CORP_CODE,
B.MEMBER_TYPE,
B.MEMBER_CLASS,
A.ACCOUNT_STATUS,
A.LEDGER_BAL,
C.SEQUENCENO
FROM DMS.ACCOUNT_MASTER				A WITH (NOLOCK)
LEFT JOIN MMS.CLIENT				B WITH (NOLOCK) ON B.MEMBER_NO = A.MEMBER_NO
LEFT JOIN DMS.ACCOUNT_BAL_HISTORY	C WITH (NOLOCK) ON C.ACCOUNT_NO = A.ACCOUNT_NO
												   AND C.ID = (SELECT MAX(ID) FROM DMS.ACCOUNT_BAL_HISTORY WHERE ACCOUNT_NO = C.ACCOUNT_NO)
												   AND C.IS_REVERSAL = 0
												   AND C.SOA_APPLICABLE = 1
-- PRODUCT CODE 001 = CCA
-- PRODUCT CODE 002 = RSD
-- PRODUCT CODE 003 = SSD
-- PRODUCT CODE 004 = TDA
-- PRODUCT CODE 005 = TDB
-- PRODUCT CODE 006 = TDC
-- PRODUCT CODE 007 = STD
WHERE A.PRODUCT_CODE = '003'
AND A.IS_CLOSE = 0
AND (SELECT COUNT(*) FROM DMS.ACCOUNT_BAL_HISTORY AA WITH(NOLOCK) WHERE AA.ACCOUNT_NO = C.ACCOUNT_NO 
     AND AA.REVERSAL_ID=C.HOST_ID AND AA.IS_REVERSAL=1)=0
GO


