DROP VIEW IF EXISTS [dbo].[VW_WrittenOffLon]

/****** Object:  View [dbo].[VW_WrittenOffLon]    Script Date: 09/01/2020 6:19:25 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE VIEW [dbo].[VW_WrittenOffLon] AS
SELECT
B.FULL_NAME 'NAME',
B.MEMBER_NO,
B.MAN_NO,
B.CORP_CODE,
A.ACCOUNT_NO,
A.PRODUCT_NAME 'LOAN TYPE',	
A.RELEASED_DATE,
A.LOAN_AMOUNT,
A.MONTHLY_AMORT,
A.MATURITY_DATE,	
A.PRINCIPAL_BALANCE,
A.INTEREST_BALANCE,
A.LOAN_BALANCE,
A.WRITTEN_OFF_DATE

FROM LMS.ACCOUNT_MASTER			A WITH(NOLOCK)
LEFT JOIN MMS.CLIENT			B WITH(NOLOCK) ON A.MEMBER_NO = B.MEMBER_NO

WHERE
DATEDIFF(MONTH,A.WRITTEN_OFF_DATE,(SELECT CURRENT_BUSINESS_DATE FROM CMN.BANK_SUNDRY)) = 0
AND (A.IS_CLOSE = 0 OR A.CLOSE_DATE IS NULL)

GO


