DROP VIEW IF EXISTS [dbo].[VW_AutoDebRegSum]
/****** Object:  View [dbo].[VW_AutoDebRegSum]    Script Date: 10/01/2020 3:00:11 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[VW_AutoDebRegSum] AS

SELECT
A.TRAN_CODE,
A.TRAN_CODE_DESCRIPTION,
B.PRODUCT_NAME,
B.PRODUCT_CODE,
C.CORP_NAME,
--NULL AS 'CREDIT',
--NULL AS 'DEBIT'
--(SELECT SUM(ISNULL(TRAN_TOTAL,0)) FROM RPT.LMS_HISTORY_CONSOLIDATED WHERE TRAN_TYPE = 0 AND TRAN_CODE = A.TRAN_CODE AND TRAN_CODE_DESCRIPTION = A.TRAN_CODE_DESCRIPTION ) 'CREDIT',	
--(SELECT SUM(ISNULL(TRAN_TOTAL,0)) FROM RPT.LMS_HISTORY_CONSOLIDATED WHERE TRAN_TYPE = 1 AND TRAN_CODE = A.TRAN_CODE AND TRAN_CODE_DESCRIPTION = A.TRAN_CODE_DESCRIPTION ) 'DEBIT'
SUM(CASE WHEN A.TRAN_TYPE = 1 THEN A.TRAN_TOTAL ELSE 0 END) AS 'CREDIT',
SUM(CASE WHEN A.TRAN_TYPE = 2 THEN A.TRAN_TOTAL ELSE 0 END) AS 'DEBIT'

FROM RPT.LMS_HISTORY_CONSOLIDATED	A WITH (NOLOCK)
LEFT JOIN LMS.ACCOUNT_MASTER		B WITH (NOLOCK) ON A.ACCOUNT_NO = B.ACCOUNT_NO
LEFT JOIN MMS.CLIENT				C WITH (NOLOCK) ON B.MEMBER_NO = C.MEMBER_NO
WHERE A.TRAN_TYPE IN (1,2)
--FOR CLARIFICATION OF AUTO DEBIT TRAN CODE
GROUP BY
A.TRAN_CODE,
A.TRAN_CODE_DESCRIPTION,
B.PRODUCT_CODE,
B.PRODUCT_NAME,
C.CORP_NAME
GO