DROP VIEW IF EXISTS [dbo].[VW_SavingsDeduct]
/****** Object:  View [dbo].[VW_SavingsDeduct]    Script Date: 14/01/2020 3:33:06 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE VIEW [dbo].[VW_SavingsDeduct] AS

SELECT 
A.MEMBER_NO,
A.ACCOUNT_NAME,
A.ACCOUNT_NO,
A.PRODUCT_SHORT_NAME 'LOAN TYPE',
A.PRINCIPAL_PAID,
A.INTEREST_PAID,
A.SD_CREDIT 'SAVINGS',
B.BILLING_GROUP,
B.BILLING_GROUP_CODE
FROM       LMS.AUTODEBIT_HISTORY A WITH(NOLOCK)
 LEFT JOIN LMS.ACCOUNT_MASTER B WITH(NOLOCK) ON A.ACCOUNT_NO = B.ACCOUNT_NO
WHERE DATEDIFF(MONTH, A.TRAN_DATE, (SELECT CURRENT_BUSINESS_DATE FROM CMN.BANK_SUNDRY)) = 0
		
GO