IF COL_LENGTH('CBDB_REPORTS.MMS.CLIENT_OTHER_INFO', 'ACCOUNT_TYPE_DESC') IS NULL
BEGIN
	ALTER TABLE CBDB_REPORTS.MMS.CLIENT_OTHER_INFO
	ADD ACCOUNT_TYPE_DESC NVARCHAR(50)
END

IF COL_LENGTH('CBDB_REPORTS.MMS.CLIENT_OTHER_INFO', 'STATUS_DESC') IS NULL
BEGIN
	ALTER TABLE CBDB_REPORTS.MMS.CLIENT_OTHER_INFO
	ADD STATUS_DESC NVARCHAR(30)
END
