IF COL_LENGTH('CBDB_STAGE.CTL.TAX_INSURANCE', 'PAYMENT_TYPE') IS NULL
BEGIN
	ALTER TABLE CBDB_STAGE.CTL.TAX_INSURANCE
	ADD PAYMENT_TYPE smallint
END

IF COL_LENGTH('CBDB_STAGE.CTL.APPRAISAL', 'REPA_STATUS') IS NULL
BEGIN
	ALTER TABLE CBDB_STAGE.CTL.APPRAISAL
	ADD REPA_STATUS smallint
END