IF EXISTS(SELECT 1 FROM CBDB_REPORTS.INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'CLIENT' AND TABLE_SCHEMA='MMS' AND COLUMN_NAME = 'GARNISH_COVERAGE_VALUE')
BEGIN
	ALTER TABLE CBDB_REPORTS.MMS.CLIENT ALTER COLUMN GARNISH_COVERAGE_VALUE NVARCHAR(200)
END


IF EXISTS(SELECT 1 FROM CBDB_REPORTS.INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'CLIENT' AND TABLE_SCHEMA='MMS' AND COLUMN_NAME = 'SPA_COVERAGE_VALUE')
BEGIN
	ALTER TABLE CBDB_REPORTS.MMS.CLIENT ALTER COLUMN SPA_COVERAGE_VALUE NVARCHAR(200)
END
