IF COL_LENGTH('CBDB_REPORTS.DMS.ACCOUNT_MASTER', 'FIXED_BALANCE') IS NULL
BEGIN
	ALTER TABLE CBDB_REPORTS.DMS.ACCOUNT_MASTER
	ADD FIXED_BALANCE DECIMAL(18,2)
END

IF COL_LENGTH('CBDB_REPORTS.DMS.ACCOUNT_MASTER', 'BUFFER_BALANCE') IS NULL
BEGIN
	ALTER TABLE CBDB_REPORTS.DMS.ACCOUNT_MASTER
	ADD BUFFER_BALANCE DECIMAL(18,2)
END

IF COL_LENGTH('CBDB_REPORTS.DMS.ACCOUNT_MASTER', 'MAX_BAL') IS NULL
BEGIN
	ALTER TABLE CBDB_REPORTS.DMS.ACCOUNT_MASTER
	ADD MAX_BAL DECIMAL(18,2)
END