ALTER TABLE CBDB_REPORTS.LMS.ACCOUNT_MASTER
	DROP COLUMN IF EXISTS APPL_STATUS

IF COL_LENGTH('CBDB_REPORTS.LMS.ACCOUNT_MASTER', 'APPL_TYPE') IS NULL
BEGIN
	ALTER TABLE CBDB_REPORTS.LMS.ACCOUNT_MASTER
	ADD APPL_TYPE nvarchar(30)
END

IF COL_LENGTH('CBDB_REPORTS.LMS.ACCOUNT_MASTER', 'APPL_TYPE_CODE') IS NULL
BEGIN
	ALTER TABLE CBDB_REPORTS.LMS.ACCOUNT_MASTER
	ADD APPL_TYPE_CODE smallint
END