DROP VIEW IF EXISTS [dbo].[VW_2ndCollLetter]

/****** Object:  View [dbo].[VW_2ndCollLetter]    Script Date: 09/01/2020 6:31:18 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE VIEW [dbo].[VW_2ndCollLetter] AS

SELECT
C.BUSINESS_DATE 'DATE',
A.FULL_NAME 'NAME',
A.LAST_NAME,
A.PREF_ADDRESS 'ADDRESS',
C.BALANCE 'BALANCE',
B.ACCOUNT_NO 'LOAN NO',
B.PRODUCT_NAME 'LOAN TYPE DESC',
C.LOAN_BALANCE 'LOAN BALANCE',
NULL 'SIGNATORY'

FROM MMS.CLIENT						A WITH(NOLOCK)
LEFT JOIN LMS.ACCOUNT_MASTER		B WITH(NOLOCK) ON A.MEMBER_NO = B.MEMBER_NO
INNER JOIN RPT.DEFICIENT_ACCOUNTS	C WITH(NOLOCK) ON B.ACCOUNT_NO = C.ACCOUNT_NO

WHERE
DATEDIFF(MONTH,C.BUSINESS_DATE,(SELECT CURRENT_BUSINESS_DATE FROM CMN.BANK_SUNDRY)) = 0 AND
C.CODE = 2

GO


