DROP VIEW IF EXISTS [dbo].[VW_SecrdLonExtInsProv]

/****** Object:  View [dbo].[VW_SecrdLonExtInsProv]    Script Date: 17/01/2020 4:02:27 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[VW_SecrdLonExtInsProv] AS

SELECT
C.MEMBER_NO 'ACCOUNT NO',
C.FULL_NAME 'NAME',
A.PRODUCT_SHORT_NAME 'LOAN TYPE',
A.ACCOUNT_NO 'LOAN NO',
A.RELEASED_DATE 'DATE GRANTED',
A.PRINCIPAL_AMOUNT 'AMOUNT GANTED',
A.INTEREST_RATE,
A.TERM,
A.LOAN_BALANCE,
B.INSURANCE_NAME,
B.POLICY_NO,
B.START_DATE,
B.END_DATE


FROM LMS.ACCOUNT_MASTER		A WITH(NOLOCK)
LEFT JOIN LMS.INSURANCE  	B WITH(NOLOCK) ON A.ACCOUNT_NO = B.ACCOUNT_NO
LEFT JOIN MMS.CLIENT		C WITH(NOLOCK) ON A.MEMBER_NO = C.MEMBER_NO














GO


