DROP VIEW IF EXISTS [dbo].[VW_UndrtkngCoMkr]

/****** Object:  View [dbo].[VW_UndrtkngCoMkr]    Script Date: 16/01/2020 9:42:56 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[VW_UndrtkngCoMkr] AS

SELECT
CAST(DAY( (SELECT CURRENT_BUSINESS_DATE FROM CMN.BANK_SUNDRY) ) AS VARCHAR(10)) +
CASE WHEN DAY( (SELECT CURRENT_BUSINESS_DATE FROM CMN.BANK_SUNDRY) ) % 10 = 1 AND DAY( (SELECT CURRENT_BUSINESS_DATE FROM CMN.BANK_SUNDRY) ) % 100 <> 11 THEN 'st'
WHEN DAY( (SELECT CURRENT_BUSINESS_DATE FROM CMN.BANK_SUNDRY) ) % 10 = 2 AND DAY( (SELECT CURRENT_BUSINESS_DATE FROM CMN.BANK_SUNDRY) ) % 100 <> 12 THEN 'nd'
WHEN DAY( (SELECT CURRENT_BUSINESS_DATE FROM CMN.BANK_SUNDRY) ) % 10 = 3 AND DAY( (SELECT CURRENT_BUSINESS_DATE FROM CMN.BANK_SUNDRY) ) % 100 <> 13 THEN 'rd'
ELSE 'th'END 'DAY',
DATENAME(MONTH, (SELECT CURRENT_BUSINESS_DATE FROM CMN.BANK_SUNDRY)) 'MONTH',
(YEAR((SELECT CURRENT_BUSINESS_DATE FROM CMN.BANK_SUNDRY)) % 100 ) + 1 'YEAR',
B.FULL_NAME 'NEW COMAKERS NAME',
C.PREF_ADDRESS 'NEW COMAKERS ADDRESS',
C.PREF_ADDRESS 'ADDRESS', 
C.FULL_NAME 'NAME',	
A.ACCOUNT_NO 'LOAN NO',
ISNULL(A.LOAN_BALANCE,0) 'BALANCE',
NULL 'SIGNATORY',
C.CORP_NAME,
A.RELEASED_DATE 'DATE GRANTED',
ISNULL(A.PRINCIPAL_AMOUNT,0) 'GROSS LN',
A.PRODUCT_NAME 'LOAN TYPE',
A.TERM,
A.INTEREST_RATE

FROM LMS.ACCOUNT_MASTER			A WITH(NOLOCK)
INNER JOIN LMS.ACCOUNT_CO_MAKER B WITH(NOLOCK) ON A.ACCOUNT_NO = B.ACCOUNT_NO
LEFT JOIN MMS.CLIENT			C WITH(NOLOCK) ON B.MEMBER_NO = C.MEMBER_NO

WHERE
B.STATUS = 1 AND
A.RELEASED_DATE IS NOT NULL









GO


