IF COL_LENGTH('CBDB_REPORTS.LMS.ACCOUNT_CO_MAKER', 'FULL_NAME') IS NULL
BEGIN
	ALTER TABLE CBDB_REPORTS.LMS.ACCOUNT_CO_MAKER
	ADD FULL_NAME VARCHAR(250)
END

IF COL_LENGTH('CBDB_REPORTS.LMS.ACCOUNT_CO_MAKER', 'LAST_NAME') IS NULL
BEGIN
	ALTER TABLE CBDB_REPORTS.LMS.ACCOUNT_CO_MAKER
	ADD LAST_NAME VARCHAR(100)
END

IF COL_LENGTH('CBDB_REPORTS.LMS.ACCOUNT_CO_MAKER', 'FIRST_NAME') IS NULL
BEGIN
	ALTER TABLE CBDB_REPORTS.LMS.ACCOUNT_CO_MAKER
	ADD FIRST_NAME VARCHAR(100)
END

IF COL_LENGTH('CBDB_REPORTS.LMS.ACCOUNT_CO_MAKER', 'MIDDLE_NAME') IS NULL
BEGIN
	ALTER TABLE CBDB_REPORTS.LMS.ACCOUNT_CO_MAKER
	ADD MIDDLE_NAME VARCHAR(100)
END

IF COL_LENGTH('CBDB_REPORTS.LMS.ACCOUNT_CO_MAKER', 'EXTN_NAME') IS NULL
BEGIN
	ALTER TABLE CBDB_REPORTS.LMS.ACCOUNT_CO_MAKER
	ADD EXTN_NAME VARCHAR(50)
END

