ALTER TABLE CBDB_REPORTS.LMS.ACCOUNT_MASTER
	ALTER COLUMN WRITE_OFF_BOARD_RES_NO NVARCHAR(50)

UPDATE CBDB_REPORTS.LMS.ACCOUNT_MASTER
	SET WRITE_OFF_BOARD_RES_NO = NULL
WHERE WRITE_OFF_BOARD_RES_NO = '0'