
DROP TABLE IF EXISTS CBDB_REPORTS.CMN.LHC_TRAN_CONFIG
CREATE TABLE CBDB_REPORTS.CMN.LHC_TRAN_CONFIG(
ID BIGINT IDENTITY,
TRAN_CODE INT PRIMARY KEY,
TRAN_NATURE INT,
TRAN_NATURE_DESC NVARCHAR(50),
IS_CHILD BIT,
IS_ADJ BIT,
IS_PAYMENT BIT
)
DROP INDEX IF EXISTS LHC_TRAN_CFG_IDX ON CBDB_REPORTS.CMN.LHC_TRAN_CONFIG
CREATE INDEX LHC_TRAN_CFG_IDX ON CBDB_REPORTS.CMN.LHC_TRAN_CONFIG(TRAN_NATURE,IS_CHILD)

DROP INDEX IF EXISTS IDX_TRAN_CODE ON CBDB_REPORTS.CMN.LHC_TRAN_CONFIG
CREATE INDEX IDX_TRAN_CODE ON CBDB_REPORTS.CMN.LHC_TRAN_CONFIG(TRAN_CODE)

TRUNCATE TABLE CBDB_REPORTS.CMN.LHC_TRAN_CONFIG
INSERT INTO CBDB_REPORTS.CMN.LHC_TRAN_CONFIG(TRAN_CODE, TRAN_NATURE, TRAN_NATURE_DESC, IS_CHILD, IS_ADJ, IS_PAYMENT) VALUES  (  2833,8,'OTHER',1,0,0)
INSERT INTO CBDB_REPORTS.CMN.LHC_TRAN_CONFIG(TRAN_CODE, TRAN_NATURE, TRAN_NATURE_DESC, IS_CHILD, IS_ADJ, IS_PAYMENT) VALUES  (  2836,1,'INTEREST',1,0,0)
INSERT INTO CBDB_REPORTS.CMN.LHC_TRAN_CONFIG(TRAN_CODE, TRAN_NATURE, TRAN_NATURE_DESC, IS_CHILD, IS_ADJ, IS_PAYMENT) VALUES  (  2841,8,'OTHER',1,0,0)
INSERT INTO CBDB_REPORTS.CMN.LHC_TRAN_CONFIG(TRAN_CODE, TRAN_NATURE, TRAN_NATURE_DESC, IS_CHILD, IS_ADJ, IS_PAYMENT) VALUES  (  2843,1,'INTEREST',1,0,0)
INSERT INTO CBDB_REPORTS.CMN.LHC_TRAN_CONFIG(TRAN_CODE, TRAN_NATURE, TRAN_NATURE_DESC, IS_CHILD, IS_ADJ, IS_PAYMENT) VALUES  (  2845,8,'OTHER',1,0,0)
INSERT INTO CBDB_REPORTS.CMN.LHC_TRAN_CONFIG(TRAN_CODE, TRAN_NATURE, TRAN_NATURE_DESC, IS_CHILD, IS_ADJ, IS_PAYMENT) VALUES  (  2847,1,'INTEREST',1,0,0)
INSERT INTO CBDB_REPORTS.CMN.LHC_TRAN_CONFIG(TRAN_CODE, TRAN_NATURE, TRAN_NATURE_DESC, IS_CHILD, IS_ADJ, IS_PAYMENT) VALUES  (  2838,9,'HANDLING FEE',1,0,0)
INSERT INTO CBDB_REPORTS.CMN.LHC_TRAN_CONFIG(TRAN_CODE, TRAN_NATURE, TRAN_NATURE_DESC, IS_CHILD, IS_ADJ, IS_PAYMENT) VALUES  (  2806,3,'PENALTY',1,0,0)
INSERT INTO CBDB_REPORTS.CMN.LHC_TRAN_CONFIG(TRAN_CODE, TRAN_NATURE, TRAN_NATURE_DESC, IS_CHILD, IS_ADJ, IS_PAYMENT) VALUES  (  2832,1,'INTEREST',1,0,0)
INSERT INTO CBDB_REPORTS.CMN.LHC_TRAN_CONFIG(TRAN_CODE, TRAN_NATURE, TRAN_NATURE_DESC, IS_CHILD, IS_ADJ, IS_PAYMENT) VALUES  (  2807,2,'AIR',1,0,0)
INSERT INTO CBDB_REPORTS.CMN.LHC_TRAN_CONFIG(TRAN_CODE, TRAN_NATURE, TRAN_NATURE_DESC, IS_CHILD, IS_ADJ, IS_PAYMENT) VALUES  (  2808,1,'INTEREST',1,0,0)
INSERT INTO CBDB_REPORTS.CMN.LHC_TRAN_CONFIG(TRAN_CODE, TRAN_NATURE, TRAN_NATURE_DESC, IS_CHILD, IS_ADJ, IS_PAYMENT) VALUES  (  3203,4,'SD',1,0,0)
INSERT INTO CBDB_REPORTS.CMN.LHC_TRAN_CONFIG(TRAN_CODE, TRAN_NATURE, TRAN_NATURE_DESC, IS_CHILD, IS_ADJ, IS_PAYMENT) VALUES  (  9031,6,'AP',1,0,0)
INSERT INTO CBDB_REPORTS.CMN.LHC_TRAN_CONFIG(TRAN_CODE, TRAN_NATURE, TRAN_NATURE_DESC, IS_CHILD, IS_ADJ, IS_PAYMENT) VALUES  (  2835,8,'OTHER',1,0,0)
INSERT INTO CBDB_REPORTS.CMN.LHC_TRAN_CONFIG(TRAN_CODE, TRAN_NATURE, TRAN_NATURE_DESC, IS_CHILD, IS_ADJ, IS_PAYMENT) VALUES  (  2837,1,'INTEREST',1,0,0)
INSERT INTO CBDB_REPORTS.CMN.LHC_TRAN_CONFIG(TRAN_CODE, TRAN_NATURE, TRAN_NATURE_DESC, IS_CHILD, IS_ADJ, IS_PAYMENT) VALUES  (  2842,8,'OTHER',1,0,0)
INSERT INTO CBDB_REPORTS.CMN.LHC_TRAN_CONFIG(TRAN_CODE, TRAN_NATURE, TRAN_NATURE_DESC, IS_CHILD, IS_ADJ, IS_PAYMENT) VALUES  (  2844,1,'INTEREST',1,0,0)
INSERT INTO CBDB_REPORTS.CMN.LHC_TRAN_CONFIG(TRAN_CODE, TRAN_NATURE, TRAN_NATURE_DESC, IS_CHILD, IS_ADJ, IS_PAYMENT) VALUES  (  2846,8,'OTHER',1,0,0)
INSERT INTO CBDB_REPORTS.CMN.LHC_TRAN_CONFIG(TRAN_CODE, TRAN_NATURE, TRAN_NATURE_DESC, IS_CHILD, IS_ADJ, IS_PAYMENT) VALUES  (  2848,1,'INTEREST',1,0,0)
INSERT INTO CBDB_REPORTS.CMN.LHC_TRAN_CONFIG(TRAN_CODE, TRAN_NATURE, TRAN_NATURE_DESC, IS_CHILD, IS_ADJ, IS_PAYMENT) VALUES  (  2839,9,'HANDLING FEE',1,0,0)
INSERT INTO CBDB_REPORTS.CMN.LHC_TRAN_CONFIG(TRAN_CODE, TRAN_NATURE, TRAN_NATURE_DESC, IS_CHILD, IS_ADJ, IS_PAYMENT) VALUES  (  2816,3,'PENALTY',1,0,0)
INSERT INTO CBDB_REPORTS.CMN.LHC_TRAN_CONFIG(TRAN_CODE, TRAN_NATURE, TRAN_NATURE_DESC, IS_CHILD, IS_ADJ, IS_PAYMENT) VALUES  (  2834,1,'INTEREST',1,0,0)
INSERT INTO CBDB_REPORTS.CMN.LHC_TRAN_CONFIG(TRAN_CODE, TRAN_NATURE, TRAN_NATURE_DESC, IS_CHILD, IS_ADJ, IS_PAYMENT) VALUES  (  2817,2,'AIR',1,0,0)
INSERT INTO CBDB_REPORTS.CMN.LHC_TRAN_CONFIG(TRAN_CODE, TRAN_NATURE, TRAN_NATURE_DESC, IS_CHILD, IS_ADJ, IS_PAYMENT) VALUES  (  2815,1,'INTEREST',1,0,0)
INSERT INTO CBDB_REPORTS.CMN.LHC_TRAN_CONFIG(TRAN_CODE, TRAN_NATURE, TRAN_NATURE_DESC, IS_CHILD, IS_ADJ, IS_PAYMENT) VALUES  (  3240,4,'SD',1,0,0)
INSERT INTO CBDB_REPORTS.CMN.LHC_TRAN_CONFIG(TRAN_CODE, TRAN_NATURE, TRAN_NATURE_DESC, IS_CHILD, IS_ADJ, IS_PAYMENT) VALUES  (  9034,6,'AP',1,0,0)
INSERT INTO CBDB_REPORTS.CMN.LHC_TRAN_CONFIG(TRAN_CODE, TRAN_NATURE, TRAN_NATURE_DESC, IS_CHILD, IS_ADJ, IS_PAYMENT) VALUES  (  2607,0,'PRINCIPAL',0,0,1)
INSERT INTO CBDB_REPORTS.CMN.LHC_TRAN_CONFIG(TRAN_CODE, TRAN_NATURE, TRAN_NATURE_DESC, IS_CHILD, IS_ADJ, IS_PAYMENT) VALUES  (  2609,0,'PRINCIPAL',0,0,1)
INSERT INTO CBDB_REPORTS.CMN.LHC_TRAN_CONFIG(TRAN_CODE, TRAN_NATURE, TRAN_NATURE_DESC, IS_CHILD, IS_ADJ, IS_PAYMENT) VALUES  (  2955,0,'PRINCIPAL',0,0,1)
INSERT INTO CBDB_REPORTS.CMN.LHC_TRAN_CONFIG(TRAN_CODE, TRAN_NATURE, TRAN_NATURE_DESC, IS_CHILD, IS_ADJ, IS_PAYMENT) VALUES  (  2610,0,'PRINCIPAL',0,0,1)
INSERT INTO CBDB_REPORTS.CMN.LHC_TRAN_CONFIG(TRAN_CODE, TRAN_NATURE, TRAN_NATURE_DESC, IS_CHILD, IS_ADJ, IS_PAYMENT) VALUES  (  2613,0,'PRINCIPAL',0,0,1)
INSERT INTO CBDB_REPORTS.CMN.LHC_TRAN_CONFIG(TRAN_CODE, TRAN_NATURE, TRAN_NATURE_DESC, IS_CHILD, IS_ADJ, IS_PAYMENT) VALUES  (  2956,0,'PRINCIPAL',0,0,1)
INSERT INTO CBDB_REPORTS.CMN.LHC_TRAN_CONFIG(TRAN_CODE, TRAN_NATURE, TRAN_NATURE_DESC, IS_CHILD, IS_ADJ, IS_PAYMENT) VALUES  (  2614,0,'PRINCIPAL',0,0,1)
INSERT INTO CBDB_REPORTS.CMN.LHC_TRAN_CONFIG(TRAN_CODE, TRAN_NATURE, TRAN_NATURE_DESC, IS_CHILD, IS_ADJ, IS_PAYMENT) VALUES  (  2615,0,'PRINCIPAL',0,0,1)
INSERT INTO CBDB_REPORTS.CMN.LHC_TRAN_CONFIG(TRAN_CODE, TRAN_NATURE, TRAN_NATURE_DESC, IS_CHILD, IS_ADJ, IS_PAYMENT) VALUES  (  2612,0,'PRINCIPAL',0,0,1)
INSERT INTO CBDB_REPORTS.CMN.LHC_TRAN_CONFIG(TRAN_CODE, TRAN_NATURE, TRAN_NATURE_DESC, IS_CHILD, IS_ADJ, IS_PAYMENT) VALUES  (  2617,0,'PRINCIPAL',0,0,1)
INSERT INTO CBDB_REPORTS.CMN.LHC_TRAN_CONFIG(TRAN_CODE, TRAN_NATURE, TRAN_NATURE_DESC, IS_CHILD, IS_ADJ, IS_PAYMENT) VALUES  (  2621,0,'PRINCIPAL',0,0,1)
INSERT INTO CBDB_REPORTS.CMN.LHC_TRAN_CONFIG(TRAN_CODE, TRAN_NATURE, TRAN_NATURE_DESC, IS_CHILD, IS_ADJ, IS_PAYMENT) VALUES  (  2623,0,'PRINCIPAL',0,0,1)
INSERT INTO CBDB_REPORTS.CMN.LHC_TRAN_CONFIG(TRAN_CODE, TRAN_NATURE, TRAN_NATURE_DESC, IS_CHILD, IS_ADJ, IS_PAYMENT) VALUES  (  2624,0,'PRINCIPAL',0,0,1)
INSERT INTO CBDB_REPORTS.CMN.LHC_TRAN_CONFIG(TRAN_CODE, TRAN_NATURE, TRAN_NATURE_DESC, IS_CHILD, IS_ADJ, IS_PAYMENT) VALUES  (  2626,0,'PRINCIPAL',0,0,1)
INSERT INTO CBDB_REPORTS.CMN.LHC_TRAN_CONFIG(TRAN_CODE, TRAN_NATURE, TRAN_NATURE_DESC, IS_CHILD, IS_ADJ, IS_PAYMENT) VALUES  (  2627,0,'PRINCIPAL',0,0,1)
INSERT INTO CBDB_REPORTS.CMN.LHC_TRAN_CONFIG(TRAN_CODE, TRAN_NATURE, TRAN_NATURE_DESC, IS_CHILD, IS_ADJ, IS_PAYMENT) VALUES  (  2628,0,'PRINCIPAL',0,0,1)
INSERT INTO CBDB_REPORTS.CMN.LHC_TRAN_CONFIG(TRAN_CODE, TRAN_NATURE, TRAN_NATURE_DESC, IS_CHILD, IS_ADJ, IS_PAYMENT) VALUES  (  2640,1,'INTEREST',0,0,0)
INSERT INTO CBDB_REPORTS.CMN.LHC_TRAN_CONFIG(TRAN_CODE, TRAN_NATURE, TRAN_NATURE_DESC, IS_CHILD, IS_ADJ, IS_PAYMENT) VALUES  (  2697,0,'PRINCIPAL',0,0,1)
INSERT INTO CBDB_REPORTS.CMN.LHC_TRAN_CONFIG(TRAN_CODE, TRAN_NATURE, TRAN_NATURE_DESC, IS_CHILD, IS_ADJ, IS_PAYMENT) VALUES  (  2719,0,'PRINCIPAL',0,0,1)
INSERT INTO CBDB_REPORTS.CMN.LHC_TRAN_CONFIG(TRAN_CODE, TRAN_NATURE, TRAN_NATURE_DESC, IS_CHILD, IS_ADJ, IS_PAYMENT) VALUES  (  2721,0,'PRINCIPAL',0,0,1)
INSERT INTO CBDB_REPORTS.CMN.LHC_TRAN_CONFIG(TRAN_CODE, TRAN_NATURE, TRAN_NATURE_DESC, IS_CHILD, IS_ADJ, IS_PAYMENT) VALUES  (  2722,0,'PRINCIPAL',0,0,1)
INSERT INTO CBDB_REPORTS.CMN.LHC_TRAN_CONFIG(TRAN_CODE, TRAN_NATURE, TRAN_NATURE_DESC, IS_CHILD, IS_ADJ, IS_PAYMENT) VALUES  (  2730,0,'PRINCIPAL',0,0,1)
INSERT INTO CBDB_REPORTS.CMN.LHC_TRAN_CONFIG(TRAN_CODE, TRAN_NATURE, TRAN_NATURE_DESC, IS_CHILD, IS_ADJ, IS_PAYMENT) VALUES  (  2723,0,'PRINCIPAL',0,0,1)

