IF NOT EXISTS (SELECT 1 FROM CBDB_REPORTS.sys.indexes WHERE name = 'LMS_ABH_INDEX')
BEGIN
	CREATE NONCLUSTERED INDEX [LMS_ABH_INDEX]
		ON CBDB_REPORTS.[LMS].[ACCT_BAL_HISTORY] ([ACCOUNT_NO],[BUSINESS_DATE],[SEQ_NO],[USER_NAME])
	END
GO