DECLARE @BIZDATE DATE = '2019-09-30'
SELECT
FORMAT(@BIZDATE, 'MMyyyy') AS MMYEAR,
'CREATE' AS 'REMARKS',
COUNT(B.MEMBER_NO) AS 'COUNT',
COUNT(C.MEMBER_NO) AS 'SP_COUNT'
FROM MMS.CLIENT A WITH(NOLOCK)
LEFT JOIN
 (SELECT MEMBER_NO 
  FROM MMS.CLIENT WITH(NOLOCK) WHERE DATEDIFF(MM, DBP_ENROLL_DATE,@BIZDATE) = 0) B
 ON A.MEMBER_NO = B.MEMBER_NO
LEFT JOIN
 (SELECT MEMBER_NO FROM MMS.CLIENT WHERE DATEDIFF(MM, SPS_DBP_ENROLL_DATE,@BIZDATE) = 0) C
 ON A.MEMBER_NO = C.MEMBER_NO

 UNION ALL

 SELECT
FORMAT(@BIZDATE, 'MMyyyy') AS MMYEAR,
'DELETE' AS 'REMARKS',
COUNT(B.MEMBER_NO) AS 'COUNT',
COUNT(C.MEMBER_NO) AS 'SP_COUNT'
FROM MMS.CLIENT A WITH(NOLOCK)
LEFT JOIN
 (SELECT MEMBER_NO 
  FROM MMS.CLIENT WITH(NOLOCK) WHERE DATEDIFF(MM, DBP_END_DATE,@BIZDATE) = 0) B
 ON A.MEMBER_NO = B.MEMBER_NO
LEFT JOIN
 (SELECT MEMBER_NO FROM MMS.CLIENT WHERE DATEDIFF(MM, SPS_DBP_END_DATE,@BIZDATE) = 0) C
 ON A.MEMBER_NO = C.MEMBER_NO