IF NOT EXISTS (SELECT TOP 1 ID FROM CBDB_REPORTS.RPT.REPORT_GENERATOR WHERE FILE_NAME = 'DTRBatch')
BEGIN
	INSERT INTO CBDB_REPORTS.RPT.REPORT_GENERATOR
		  (FILE_NAME ,DIRECTORY				  ,EXPORT_TYPE ,FREQUENCY ,DEPARTMENT ,COPY_EXPRESSION)
	VALUES('DTRBatch','DAILY\CSV\DTRBatch.mrt','CSV'	   ,'DAILY'	  ,'BRC'	  ,'BRC')
END