IF COL_LENGTH('CBDB_REPORTS.LMS.REMITTANCE', 'REMITTANCE_TYPE_DESC') IS NULL
BEGIN
	ALTER TABLE CBDB_REPORTS.LMS.REMITTANCE
	ADD REMITTANCE_TYPE_DESC nvarchar(100)
END

IF COL_LENGTH('CBDB_REPORTS.LMS.REMITTANCE', 'PRODUCT_CATEGORY') IS NULL
BEGIN
	ALTER TABLE CBDB_REPORTS.LMS.REMITTANCE
	ADD PRODUCT_CATEGORY smallint
END

IF COL_LENGTH('CBDB_REPORTS.LMS.REMITTANCE', 'SEQUENCE_NO') IS NULL
BEGIN
	ALTER TABLE CBDB_REPORTS.LMS.REMITTANCE
ADD SEQUENCE_NO bigint
END
