--DROP VIEW IF EXISTS [dbo].[VW_AppRequest]

--/****** Object:  View [dbo].[VW_AppRequest]    Script Date: 20/02/2020 6:38:01 PM ******/
--SET ANSI_NULLS ON
--GO

--SET QUOTED_IDENTIFIER ON
--GO

--CREATE VIEW [dbo].[VW_AppRequest] AS
SELECT
C.MEMBER_NO,
C.BILLING_GROUP_CODE,
C.LAST_NAME,
C.FIRST_NAME,
C.MIDDLE_NAME,
A.COLLATERAL_ID,
B.TCT_NO,
A.REPA_NO,
A.REPA_STATUS_DESC,
A.ENCODED_DATE,
A.RECEIVED_DATE,
A.APPRAISAL_REF_NO,
C.RELEASED_DATE,
A.DELIVERED_DATE,
A.USER_ID,
A.ACKNOWLEDGE_RECEIPT,
A.PAYMENT_DATE,
A.FEE_PAID,
A.BILLING_DATE,
A.BILLING_AMOUNT,
A.REMARKS
FROM LMS.APPRAISAL A WITH(NOLOCK)
LEFT JOIN LMS.COLLATERAL B WITH(NOLOCK) ON A.COLLATERAL_ID = B.COLLATERAL_ID AND A.ACCOUNT_NO = B.ACCOUNT_NO
LEFT JOIN LMS.ACCOUNT_MASTER C WITH(NOLOCK) ON A.ACCOUNT_NO = C.ACCOUNT_NO

WHERE --A.IS_TERMINATED = 0 -- VALIDATE NOT TERMINATED
C.IS_CLOSE=0 AND C.RELEASED_DATE IS NOT NULL   --NEED TO HAVE ADDITIOANL VALIDATION FOR THE REPA STATUS(PENDING WITH HOST)
ORDER BY COLLATERAL_ID
GO

SELECT * FROM CBDB_COLLATERAL.CBDB_COLLATERAL_ADMIN.COLLATERAL_INFO
SELECT * FROM CBDB_COLLATERAL.CBDB_COLLATERAL_ADMIN.PROPERTY WHERE PROPERTY_GUID = '100019421ID10290283-TCT-00000001'