DROP VIEW IF EXISTS [dbo].[VW_SumLonColl]
/****** Object:  View [dbo].[VW_SumLonColl]    Script Date: 13/02/2020 10:16:13 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[VW_SumLonColl] AS
SELECT
B.ACCOUNT_NO,
A.OR_NO,
C.FULL_NAME 'NAME',
A.TRAN_CODE 'TRAN CODE',	
A.TRAN_CODE_DESCRIPTION 'TRAN DESC',
A.TRAN_TOTAL 'TOTAL AMOUNT',	
A.PRINCIPAL,
A.INTEREST,
A.AP 'A/P',
A.AR 'A/R',
A.PENALTY,
NULL 'OTHER CHARGES'

FROM RPT.LMS_HISTORY_CONSOLIDATED		A WITH(NOLOCK)
LEFT JOIN LMS.ACCOUNT_MASTER			B WITH(NOLOCK) ON A.ACCOUNT_NO = B.ACCOUNT_NO
LEFT JOIN MMS.CLIENT					C WITH(NOLOCK) ON B.MEMBER_NO = C.MEMBER_NO
----COLLECTION TRAN CODES NOT YET AVAILABLE 2019-12-06
WHERE DATEDIFF(DAY, A.BUSINESS_DATE, (SELECT CURRENT_BUSINESS_DATE FROM CMN.BANK_SUNDRY)) = 0
GO


