SELECT
'IF COL_LENGTH(''CBDB_REPORTS.' + TABLE_SCHEMA + '.' + TABLE_NAME + ''', ''' + COLUMN_NAME + ''') IS NOT NULL BEGIN ' +
'ALTER TABLE CBDB_REPORTS.' + TABLE_SCHEMA + '.' + TABLE_NAME + ' ALTER COLUMN ' + COLUMN_NAME + ' ' + DATA_TYPE +
CASE WHEN CHARACTER_MAXIMUM_LENGTH IS NOT NULL 
	THEN '('+ CAST(CHARACTER_MAXIMUM_LENGTH AS varchar(MAX)) +') NULL END' 
	ELSE ' NULL END' 
END AS Q
,* FROM [INFORMATION_SCHEMA].[COLUMNS] 
WHERE is_nullable = 'NO' 
AND TABLE_SCHEMA NOT IN ('dbo', 'rpt') 
AND COLUMN_NAME NOT IN ('HEADER_ID','ID')
ORDER BY TABLE_SCHEMA, TABLE_NAME

