INSERT INTO CBDB_REPORTS.MMS.ADDRESS (HEADER_ID, MEMBER_NO, ADDRESS_TYPE, ADDRESS1, TOWN, CITY, COUNTRY, LANDLINE, RTS, INACTIVE, PREFFERED)
       SELECT HEADER_ID, CIF_NO, ADDRESS_TYPE, ADDRESS1, TOWN, CITY, COUNTRY, LANDLINE_PREFIX + LANDLINE_NUMBER AS 'LANDLINE', NULL AS 'RTS', IIF(STATUS = 1, 0, 1) AS 'INACTIVE', PREFERRED_ADDRESS FROM CBDB_STAGE.MMS.ADDRESS


INSERT INTO CBDB_REPORTS.MMS.CLIENT_STATUS_HISTORY (HEADER_ID, MEMBER_NO, STATUS_FROM, STATUS_TO, MAINT_DATE, MAINT_BY, MAINT_REASON)
	   SELECT HEADER_ID, CIF_NO, STATUS_FROM, STATUS_TO, LAST_UPDATED_DATE, LAST_UPDATED_BY, REASON_CODE /*DESCRIPTIVE*/ FROM CBDB_STAGE.MMS.CLIENT_STATUS_HISTORY

--MMS.FAMILY GROUP IS NOT PRESENT IN STAGE

INSERT INTO CBDB_REPORTS.MMS.PEP_INFO (HEADER_ID, PRIMARY_MEMBER_NO, NAME_PEP_ASSOC, POSTION, ENTITY, RELATIONSHIP)
	   SELECT HEADER_ID, CIF_NO, ISNULL(LAST_NAME,'') + ' ' + ISNULL(FIRST_NAME,'') + ' ' + ISNULL(SUFFIX_NAME,'') + ' ' + ISNULL(MIDDLE_NAME,'') AS FULL_NAME, POSITION, ENTITY, RELATIONSHIP_CODE /*DESCRIPTIVE*/ FROM CBDB_STAGE.MMS.CLIENT_PEP

INSERT INTO CBDB_REPORTS.MMS.PRIM_SEC_XREF (HEADER_ID, PRIMARY_MEMBER_NO, SEC_MEMBER_NO)
	   SELECT HEADER_ID, CIF_NO, RELATED_CIF_NO FROM CBDB_STAGE.MMS.CLIENT_RELATION

INSERT INTO CBDB_REPORTS.MMS.RELATIONSHIP (HEADER_ID, PRIMARY_MEMBER_NO, MEMBER_NO, RELATION_TYPE, RELATIONSHIP, FNAME, MNAME, LNAME, EXTN_NAME, BIRTHDATE, DBP)
	   SELECT HEADER_ID, CIF_NO, RELATED_CIF_NO, RELATION_TYPE, RELATIONSHIP_CODE /*DESCRIPTIVE*/, FIRST_NAME, MIDDLE_NAME, LAST_NAME, SUFFIX_NAME, BIRTH_DATE, NULL AS 'DBP' FROM CBDB_STAGE.MMS.CLIENT_RELATION
