/****************************LMS.ACCOUNT_MASTER****************************************/
SELECT * FROM CBDB_REPORTS.LMS.ACCOUNT_MASTER
--CLOSE_DATE
SELECT COUNT(1) FROM CBDB_STAGE.LMS.ACCOUNT_INFO WHERE CLOSE_DATE IS NULL
SELECT COUNT(1) FROM CBDB_REPORTS.LMS.ACCOUNT_MASTER WHERE CLOSE_DATE IS NULL
SELECT COUNT(1) FROM CBDB_LOANS.CBDB_LOANS_ADMIN.ACCOUNT_INFO WHERE CLOSE_DATE IS NULL

--WRITE_OFF_DATE
SELECT COUNT(1) FROM CBDB_STAGE.LMS.ACCOUNT_INFO WHERE WRITE_OFF_DATE IS NULL
SELECT COUNT(1) FROM CBDB_REPORTS.LMS.ACCOUNT_MASTER WHERE WRITTEN_OFF_DATE IS NULL
SELECT COUNT(1) FROM CBDB_LOANS.CBDB_LOANS_ADMIN.ACCOUNT_INFO WHERE WRITE_OFF_DATE IS NULL

--LAST_TXT_DATE
SELECT * FROM CBDB_STAGE.LMS.ACCOUNT_INFO WHERE WRITE_OFF_DATE IS NULL
SELECT * FROM CBDB_REPORTS.LMS.ACCOUNT_MASTER WHERE WRITTEN_OFF_DATE IS NULL
SELECT * FROM CBDB_LOANS.CBDB_LOANS_ADMIN.ACCOUNT_INFO WHERE WRITE_OFF_DATE IS NULL

--TXR_DATE|TRANSFER DATE
SELECT * FROM CBDB_STAGE.LMS.ACCOUNT_CO_MAKER
SELECT * FROM CBDB_LOANS.CBDB_LOANS_ADMIN.ACCOUNT_CO_MAKER

--ORIGINAL_BORROWER

--LAST_STAT_CHANGE
SELECT * FROM CBDB_LOANS.CBDB_LOANS_ADMIN.ACCOUNT_BALANCE_HISTORY
SELECT * FROM CBDB_LOANS.CBDB_LOANS_ADMIN.ACCOUNT_INFO

--CATEGORY
SELECT * FROM CBDB_STAGE.LMS.PRODUCT_OTHER_CONFIG POC
SELECT * FROM CBDB_STAGE.LMS.PRODUCT

/****************************LMS.ACCOUNT_PDC****************************************/
SELECT * FROM CBDB_REPORTS.LMS.ACCOUNT_PDC
SELECT * FROM CBDB_LOANS.CBDB_LOANS_ADMIN.ACCOUNT_PDC

/****************************LMS.ACCT_BAL_HISTORY****************************************/
SELECT * FROM CBDB_REPORTS.LMS.ACCT_BAL_HISTORY
--OR AR FIELDS
SELECT * FROM CMN.BIZ_JOURNAL
--HOST_ID
SELECT * FROM CBDB_STAGE.LMS.ACCOUNT_BALANCE_HISTORY WHERE HOST_ID IS NOT NULL

/****************************LMS.ACCT_BAL_HISTORY****************************************/
SELECT * FROM CBDB_REPORTS.LMS.COLLATERAL
SELECT * FROM CBDB_STAGE.LMS.ACCOUNT_COLLATERAL

/****************************LMS.LMS_APPRAISAL****************************************/
select * from cbdb_reports.lms.APPRAISAL
SELECT * FROM CBDB_STAGE.CTL.APPRAISAL


/****************************LMS.ACCOUNT_CO_MAKER****************************************/
SELECT * FROM CBDB_STAGE.LMS.ACCOUNT_CO_MAKER
SELECT  * FROM CBDB_LOANS.CBDB_LOANS_ADMIN.ACCOUNT_CO_MAKER




/****************************DMS.ACCOUNT_MASTER****************************************/
SELECT * FROM CBDB_REPORTS.DMS.ACCOUNT_MASTER
--ACCOUNT_TYPE TEMPORARY NULL
--CAPCON_CEILING
SELECT * FROM CBDB_STAGE.DMS.ACCOUNT_INFO WHERE CAPCON_CEILING IS NOT NULL
SELECT * FROM CBDB_DEPOSIT.CBDB_DEPOSIT_ADMIN.ACCOUNT_INFO WHERE CAPCON_CEILING IS NOT NULL

--LAST_INACTIVE_ANNIV_DATE PENDING

--PLACEMENT FIELDS
SELECT * FROM CBDB_DEPOSIT.CBDB_DEPOSIT_ADMIN.ACCOUNT_PLACEMENT



/****************************DMS.ACCT_ANNUAL_BALANCE****************************************/
SELECT * FROM CBDB_REPORTS.DMS.ACCT_ANNUAL_BALANCE
SELECT * FROM CBDB_DEPOSIT.CBDB_DEPOSIT_ADMIN.ACCOUNT_ANNUAL_BALANCE


/****************************DMS.ACCOUNT_BALANCE_HISTORY****************************************/
SELECT * FROM CBDB_REPORTS.DMS.ACCOUNT_BAL_HISTORY
SELECT * FROM CBDB_DEPOSIT.CBDB_DEPOSIT_ADMIN.ACCOUNT_BALANCE_HISTORY

--HOST_ID
SELECT * FROM CBDB_STAGE.DMS.ACCOUNT_BALANCE_HISTORY WHERE HOST_ID IS NOT NULL

/****************************DMS.TD_ACCOUNT_INFO****************************************/
SELECT * FROM CBDB_REPORTS.DMS.TD_ACCOUNT_INFO

--LAST_CREDIT_DATE
SELECT * FROM CBDB_STAGE.DMS.ACCOUNT_PLACEMENT
SELECT * FROM CBDB_DEPOSIT.CBDB_DEPOSIT_ADMIN.ACCOUNT_PLACEMENT