USE CBDB_REPORTS
SELECT * 
FROM   INFORMATION_SCHEMA.VIEWS 
WHERE  VIEW_DEFINITION like '%PENALTY%'
ORDER by TABLE_NAME

SELECT * FROM LMS.ACCT_BAL_HISTORY

SELECT * FROM RPT.LMS_HISTORY_CONSOLIDATED

SELECT * FROM CBDB_STAGE.MMS.CLIENT

SELECT * FROM CBDB_CIF.CBDB_CIF_ADMIN.CLIENT WhERE CORP_CODE = 'MECO'